#!/usr/bin/env python3
"""Write the blog pages, two directions for each of the two live blog pages:

    blog.html            goldenpi.com/blog, redesigned (the direction we recommend)
    blog-minimal.html    goldenpi.com/blog, their layout moved onto the set's schema
    blog-post.html       one article, redesigned
    blog-post-minimal.html  one article, their layout on the set's schema

Source is production (the blog is WordPress + Soledad, the same on uatnew):
crawl/rendered/prod_blog*.html, read into JSON by crawl/blog_extract.js;
images from crawl/blog_images.sh (JPEG, 640px and 1200px for srcset). Every string, rate,
date and link below comes from those captures; content/prod_blog*.md is the
review copy.

Colour: the set's gold stays the action colour (buttons). The blog's own navy
(#19386d, their header, buttons and footer) is kept as the reading colour:
category labels, links, the summary callout, the contents rail and, on the
redesign, a navy tint over every thumbnail that lifts on hover. Their
thumbnails come from many designers (black-and-gold, white, bright blue);
the tint makes a grid of them read as one set, and it is CSS, so every future
upload gets it with no image editing. CSS is the BLOG block at the end of
final.css.

    python3 pages/_blog.py && python3 pages/_build.py
"""
import html
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RENDERED = os.path.join(ROOT, "crawl", "rendered")
SNAPSHOT = "2026-10-05"
esc = html.escape

from _prod import HEAD, SHELL, FOOTER, SCRIPTS  # noqa: E402  (same shell as the product pages)

LANDING = json.load(open(os.path.join(RENDERED, "prod_blog.json"), encoding="utf-8"))
POST = json.load(open(os.path.join(RENDERED, "prod_blog_post.json"), encoding="utf-8"))
IMG = dict(r.split("\t")[:2] for r in open(os.path.join(ROOT, "assets", "img", "blog", "map.tsv"), encoding="utf-8").read().splitlines())
POST_URL = "https://goldenpi.com/blog/fixed-deposit/hdfc-bank-fixed-deposits-fds-and-interest-rates/"


def img_base(url):
    """Captured image URL -> local base name, as blog_images.sh wrote it."""
    if url in IMG:
        return IMG[url]
    full = re.sub(r"-\d+x\d+(\.\w+)$", r"\1", url)
    return IMG[full]


def pic(url, alt="", cls="", eager=False, sizes="(min-width: 960px) 380px, 90vw"):
    b = img_base(url)
    return ('<img%s src="../assets/img/blog/%s.jpg" srcset="../assets/img/blog/%s-640.jpg 640w, ../assets/img/blog/%s.jpg 1200w"'
            ' sizes="%s" alt="%s"%s decoding="async">') % (
        ' class="%s"' % cls if cls else "", b, b, b, sizes, esc(alt), "" if eager else ' loading="lazy"')


def local(href, minimal):
    """Point captured links at the pages this repo has; anything else stays live."""
    suffix = "-minimal" if minimal else ""
    h = href.split("?")[0].rstrip("/")
    known = {
        "https://goldenpi.com": "index.html",
        "https://goldenpi.com/corporate-bonds": "corporate-bonds.html",
        "https://goldenpi.com/collections/tax-free-bonds": "collections-tax-free-bonds.html",
        "https://goldenpi.com/bond-utsav": "bond-utsav.html",
        "https://goldenpi.com/blog": "blog%s.html" % suffix,
        POST_URL.rstrip("/"): "blog-post%s.html" % suffix,
    }
    return known.get(h, href)


def person(author):
    """'Rohit Suhag | CA | IIM Calcutta' -> ('Rohit Suhag', 'CA | IIM Calcutta').
    Their bylines use both '|' and ',' after the name."""
    m = re.match(r"^(.*?)\s*[|,]\s*(.*)$", author)
    return (m.group(1), m.group(2)) if m else (author, "")


def page(slug, title, desc, note, body, extra_js=""):
    out = HEAD.format(title=esc(title), desc=esc(desc), note=note, slug="blog", snap=SNAPSHOT)
    out = out.replace("Generated by pages/_prod.py from crawl/rendered/prod_blog.html",
                      "Generated by pages/_blog.py from crawl/rendered/prod_blog*.json")
    out = out.replace("copy in content/prod_blog.md", "copy in content/prod_blog*.md")
    out = out.replace('<body class="gp-prod">', '<body class="gp-prod gp-blog">')
    # Each thumb shows its whole image (their banners are 16:9 and 2.11:1, and
    # carry their titles to the edge), so the box's spare band is filled with
    # the same art, blurred: the small copy, as a background, set here once.
    body = re.sub(r'<span class="gp-bthumb([^"]*)"><img([^>]*?) src="\.\./assets/img/blog/([^"]+)\.jpg"',
                  r'<span class="gp-bthumb\1" style="background-image:url(../assets/img/blog/\3-640.jpg)"><img\2 src="../assets/img/blog/\3.jpg"', body)
    out += SHELL + '<main id="main-content">\n' + body + "\n</main>\n\n" + FOOTER + "\n" + SCRIPTS + extra_js
    out += "\n</body>\n</html>\n"
    open(os.path.join(HERE, slug + ".html"), "w", encoding="utf-8").write(out)
    print("wrote pages/%s.html" % slug)


TABS_JS = "<script>\n%s</script>\n" % open(os.path.join(HERE, "_tabs.js"), encoding="utf-8").read()

# Contents rail: mark the section being read. IntersectionObserver, no scroll listener.
SPY_JS = """<script>
(function () {
  var links = [].slice.call(document.querySelectorAll('.gp-btoc a[href^="#"]'));
  if (!links.length || !('IntersectionObserver' in window)) return;
  var byId = {};
  links.forEach(function (a) { byId[a.getAttribute('href').slice(1)] = a; });
  var io = new IntersectionObserver(function (entries) {
    entries.forEach(function (e) {
      if (!e.isIntersecting) return;
      links.forEach(function (a) { a.removeAttribute('aria-current'); });
      byId[e.target.id].setAttribute('aria-current', 'true');
    });
  }, { rootMargin: '-15% 0px -70% 0px' });
  Object.keys(byId).forEach(function (id) { var el = document.getElementById(id); if (el) io.observe(el); });
})();
</script>
"""

# ------------------------------------------------------------ newsletter

NEWS = """  <!-- Newsletter. Copy as on their blog; the form is not wired (their
       widget posts to their mail provider). -->
  <section class="gp-section gp-section--tight" aria-labelledby="newsletter-title">
    <div class="gp-shell">
      <div class="gp-bnews">
        <div>
          <h2 class="gp-bnews__title" id="newsletter-title">Sign up for our newsletter today</h2>
          <p class="gp-bnews__sub">Get regular updates on the latest bonds &amp; debentures from GoldenPi.</p>
        </div>
        <form class="gp-bnews__form" action="#" onsubmit="return false">
          <label class="sr-only" for="news-email">What&rsquo;s your email?</label>
          <input class="gp-bnews__input" id="news-email" type="email" name="email" placeholder="What&rsquo;s your email?" autocomplete="email" required>
          <button class="gp-btn gp-btn--primary" type="submit">Subscribe</button>
        </form>
      </div>
    </div>
  </section>
"""


def crumbs(items):
    out = []
    for label, href in items:
        out.append('<a href="%s">%s</a>' % (esc(href), esc(label)) if href else
                   '<span aria-current="page">%s</span>' % esc(label))
    return ('      <nav class="gp-bcrumb" aria-label="Breadcrumb">%s</nav>'
            % '<span aria-hidden="true">&rsaquo;</span>'.join(out))


# ================================================================ landing

def card(p, minimal, tint=True, size=""):
    """One post: 16:9 thumb (their crop), title, byline, date."""
    name, cred = person(p["author"])
    return """          <article class="gp-bcard%s">
            <a class="gp-bcard__link" href="%s">
              <span class="gp-bthumb%s">%s</span>
              <span class="gp-bcard__title">%s</span>
            </a>
            <p class="gp-bmeta">by <a href="%s">%s</a>%s</p>
            <time class="gp-bmeta" datetime="%s">%s</time>
          </article>""" % (
        size, esc(local(p["href"], minimal)), " gp-bthumb--tint" if tint else "", pic(p["img"]),
        esc(p["title"]), esc(p["authorHref"]), esc(name), ('<span class="gp-bmeta__cred"> | %s</span>' % esc(cred)) if cred else "",
        esc(p.get("datetime", "")[:10]), esc(p["date"]))


def guide(sec, minimal):
    tint = "" if minimal else " gp-bthumb--tint"
    """Their Guide block: one lead with its excerpt, four compact rows."""
    lead, rest = sec["posts"][0], sec["posts"][1:]
    name, cred = person(lead["author"])
    excerpt = re.sub(r"^\W+", "", lead["excerpt"])  # their excerpt opens with a pencil emoji
    rows = "\n".join("""            <li><a class="gp-brow" href="%s">
              <span class="gp-bthumb%s">%s</span>
              <span class="gp-brow__body"><span class="gp-brow__title">%s</span><time class="gp-bmeta">%s</time></span>
            </a></li>""" % (esc(local(p["href"], minimal)), tint, pic(p["img"]), esc(p["title"]), esc(p["date"])) for p in rest)
    return """          <div class="gp-bguide">
            <article class="gp-bcard gp-bcard--lead">
              <a class="gp-bcard__link" href="%s">
                <span class="gp-bthumb%s">%s</span>
                <span class="gp-bcard__title">%s</span>
              </a>
              <p class="gp-bmeta">by <a href="%s">%s</a>%s</p>
              <time class="gp-bmeta">%s</time>
              <p class="gp-bcard__excerpt">%s</p>
            </article>
            <ul class="gp-brows" role="list">
%s
            </ul>
          </div>""" % (esc(local(lead["href"], minimal)), tint, pic(lead["img"]), esc(lead["title"]), esc(lead["authorHref"]),
                       esc(name), ('<span class="gp-bmeta__cred"> | %s</span>' % esc(cred)) if cred else "",
                       esc(lead["date"]), esc(excerpt), rows)


def cats(cs, minimal):
    return "".join('<a class="gp-bcat" href="%s">%s</a>' % (esc(c["href"]), esc(c["label"])) for c in cs)


def search():
    return """<form class="gp-bsearch" role="search" method="get" action="https://goldenpi.com/blog/">
            <label class="sr-only" for="blog-search">Search</label>
            <input id="blog-search" type="search" name="s" placeholder="Type and hit enter..." autocomplete="off">
            <button type="submit" class="gp-bsearch__btn">Search</button>
          </form>"""


def menu_rail():
    return "\n".join('            <li><a class="gp-bchip" href="%s">%s</a></li>' % (esc(m["href"] if m["href"].startswith("http") else "https://goldenpi.com" + m["href"]), esc(m["label"]))
                     for m in LANDING["menu"])


LEAD = """        <article class="gp-blead" data-reveal>
          <a class="gp-blead__link" href="%(href)s" tabindex="-1" aria-hidden="true">
            <span class="gp-bthumb gp-bthumb--hero">%(img)s</span>
          </a>
          <div class="gp-blead__body">
            <p class="gp-bcats">%(cats)s</p>
            <h2 class="gp-blead__title"><a href="%(href)s">%(title)s</a></h2>
            <p class="gp-bmeta">by<span class="gp-bmeta__name">%(name)s</span><span class="gp-bmeta__sep" aria-hidden="true"></span><time>%(date)s</time></p>
          </div>
        </article>"""


def landing_full():
    lead, more = LANDING["slides"][0], LANDING["slides"][1:]
    latest = "\n".join("""            <li><a class="gp-brow" href="%s">
              <span class="gp-bthumb gp-bthumb--tint">%s</span>
              <span class="gp-brow__body">
                <span class="gp-bcat gp-bcat--plain">%s</span>
                <span class="gp-brow__title">%s</span>
                <time class="gp-bmeta">%s</time>
              </span>
            </a></li>""" % (esc(local(s["href"], False)), pic(s["img"]), esc(s["cats"][0]["label"]), esc(s["title"]), esc(s["date"])) for s in more)

    secs = LANDING["sections"]
    ids = [re.sub(r"\W+", "-", s["name"].lower()).strip("-") for s in secs]
    tabs = "\n".join("""            <button type="button" class="gp-tab" role="tab" id="tab-%s"
                    aria-controls="panel-%s" aria-selected="%s"%s>%s</button>""" % (
        i, i, "true" if n == 0 else "false", "" if n == 0 else ' tabindex="-1"', esc(s["name"])) for n, (i, s) in enumerate(zip(ids, secs)))
    panels = []
    for n, (i, s) in enumerate(zip(ids, secs)):
        inner = guide(s, False) if s["layout"] == "lead+list" else (
            '          <div class="gp-bgrid">\n%s\n          </div>' % "\n".join(card(p, False) for p in s["posts"]))
        panels.append("""        <div class="gp-panel gp-bpanel%s" id="panel-%s" role="tabpanel" aria-labelledby="tab-%s"%s>
%s
          <p class="gp-bpanel__more"><a href="%s">View All<span class="sr-only"> %s</span> <span aria-hidden="true">&rarr;</span></a></p>
        </div>""" % (" is-on" if n == 0 else "", i, i, "" if n == 0 else " hidden", inner, esc(s["more"]), esc(s["name"])))

    name, cred = person(LANDING["sections"][0]["posts"][0]["author"])
    body = """  <!-- ============================================================== hero -->
  <!-- DATA: their featured slider (8 posts) and the seven category blocks,
       goldenpi.com/blog captured %s. The lead is their first slide; the
       other seven slides are the Latest list. The only thumbnail in full
       colour on the page is the lead; the rest rest under the navy tint. -->
  <section class="gp-bhero">
    <div class="gp-shell">
%s
      <div class="gp-bhero__head">
        <div>
          <h1 class="gp-bhero__title">Blogs</h1>
          <p class="gp-bhero__sub">All about bonds online in India</p>
        </div>
        %s
      </div>
      <nav aria-label="Blog categories">
        <ul class="gp-bchips" role="list">
%s
        </ul>
      </nav>

      <div class="gp-bfeature">
%s
        <aside class="gp-blatest" aria-labelledby="latest-title">
          <h2 class="gp-blatest__title" id="latest-title">Latest</h2>
          <ul class="gp-brows" role="list">
%s
          </ul>
        </aside>
      </div>
    </div>
  </section>

  <!-- ========================================================= categories -->
  <!-- Their seven category blocks, in their order, as corporate-bonds' folder
       tabs (shared _tabs.js). Every panel is in the markup; the closed ones
       are [hidden], so crawlers and no-JS readers still get every post. -->
  <section class="gp-section gp-section--tight" aria-labelledby="browse-title">
    <div class="gp-shell">
      <h2 class="gp-bsec__title" id="browse-title">Browse by category</h2>
      <div>
      <div class="gp-tabs mb-0">
        <div class="gp-tabs__track" role="tablist" aria-label="Category">
          <span class="gp-tabs__ink" aria-hidden="true"></span>
%s
        </div>
      </div>
%s
      </div>
    </div>
  </section>

%s""" % (SNAPSHOT, crumbs([("Home", "index.html"), ("Blogs", "")]), search(), menu_rail(),
         LEAD % dict(href=esc(local(lead["href"], False)), img=pic(lead["img"], "HDFC Bank Fixed Deposits (FDs) and Interest Rates", eager=True, sizes="(min-width: 1024px) 700px, 100vw"),
                     cats=cats(lead["cats"], False), title=esc(lead["title"]), name=esc(name), date=esc(lead["date"])),
         latest, tabs, "\n".join(panels), NEWS)
    page("blog", LANDING["title"], LANDING["h1"],
         "Blog landing, redesigned from goldenpi.com/blog in the set's schema with the blog's navy as the reading colour.",
         body, TABS_JS)


def landing_minimal():
    slides = "\n".join("""          <li class="gp-bslide">
            <a href="%s">
              <span class="gp-bthumb">%s</span>
              <span class="gp-bcats">%s</span>
              <span class="gp-bslide__title">%s</span>
              <time class="gp-bmeta">%s</time>
            </a>
          </li>""" % (esc(local(s["href"], True)), pic(s["img"], eager=(n == 0)), "".join('<span class="gp-bcat gp-bcat--plain">%s</span>' % esc(c["label"]) for c in s["cats"]),
                      esc(s["title"]), esc(s["date"])) for n, s in enumerate(LANDING["slides"]))
    blocks = []
    for s in LANDING["sections"]:
        inner = guide(s, True) if s["layout"] == "lead+list" else (
            '        <div class="gp-bgrid">\n%s\n        </div>' % "\n".join(card(p, True, tint=False) for p in s["posts"]))
        blocks.append("""  <section class="gp-section gp-section--tight gp-bsec">
    <div class="gp-shell">
      <h2 class="gp-bsec__title gp-bsec__title--rule">%s</h2>
%s
      <p class="mt-6"><a class="gp-btn gp-btn--ghost gp-btn--sm" href="%s">View All<span class="sr-only"> %s</span> <span aria-hidden="true">&raquo;</span></a></p>
    </div>
  </section>""" % (esc(s["name"]), inner, esc(s["more"]), esc(s["name"])))
    body = """  <!-- Minimal: their page as it is (slider, then seven category blocks of
       three with View All), on the set's type, ground, cards and buttons.
       Images untouched. DATA: goldenpi.com/blog captured %s. -->
  <section class="gp-bhero gp-bhero--minimal">
    <div class="gp-shell">
%s
      <h1 class="sr-only">%s</h1>
      <ul class="gp-bslider" role="list" aria-label="Featured posts">
%s
      </ul>
    </div>
  </section>
%s
%s""" % (SNAPSHOT, crumbs([("Home", "index.html"), ("Blogs", "")]), esc(LANDING["h1"]), slides, "\n".join(blocks), NEWS)
    page("blog-minimal", LANDING["title"], LANDING["h1"],
         "Blog landing, minimal: goldenpi.com/blog's layout moved onto the set's schema.", body)


# ================================================================ article

def table(rows):
    """Their rate table. Header rows as captured; the row their copy names as
    the highest regular rate is marked."""
    head, sub, data = rows[0], rows[1], rows[2:]
    th = "".join('<th scope="col"%s>%s</th>' % (' colspan="%d"' % c["colspan"] if c["colspan"] > 1 else "", esc(c["text"])) for c in head)
    th2 = "".join('<th scope="col">%s</th>' % esc(c["text"]) for c in sub)
    body = []
    for r in data:
        top = r[0]["text"].startswith("3 Years 1 day to < 4 Years 7")
        body.append('<tr%s><th scope="row">%s</th>%s</tr>' % (
            ' class="is-top"' if top else "", esc(r[0]["text"]), "".join("<td>%s</td>" % esc(c["text"]) for c in r[1:])))
    return """          <div class="gp-btable" tabindex="0" role="region" aria-label="HDFC Bank FD rates by tenure">
            <table>
              <thead><tr>%s</tr><tr>%s</tr></thead>
              <tbody>
                %s
              </tbody>
            </table>
          </div>""" % (th, th2, "\n                ".join(body))


def article_blocks(minimal):
    out, toc = [], None
    for b in POST["blocks"]:
        t = b["type"]
        if t == "p":
            h = b["html"]
            for href in re.findall(r'href="([^"]+)"', h):
                h = h.replace('href="%s"' % href, 'href="%s"' % esc(local(html.unescape(href), minimal)))
            if h.startswith("Fixed returns do not constitute"):
                out.append('          <p class="gp-bdisclaimer">%s</p>' % h)
            else:
                out.append("          <p>%s</p>" % h)
        elif t in ("h2", "h3"):
            out.append('          <%s%s>%s</%s>' % (t, ' id="%s"' % b["id"] if b["id"] else "", esc(b["text"]), t))
        elif t == "table":
            out.append(table(b["rows"]))
        elif t == "ul":
            out.append('          <ul class="gp-bterms">\n%s\n          </ul>' % "\n".join("            <li>%s</li>" % (
                re.sub(r'href="([^"]+)"', lambda m: 'href="%s" rel="noopener"' % m.group(1), i)) for i in b["items"]))
        elif t == "latest":
            out.append('          <ul class="gp-bmini" role="list">\n%s\n          </ul>' % "\n".join(
                '            <li><a href="%s"><span class="gp-bthumb%s">%s</span><span>%s</span></a></li>' % (
                    esc(local(p["href"], minimal)), "" if minimal else " gp-bthumb--tint", pic(p["img"]), esc(p["title"])) for p in b["posts"]))
        elif t == "box":
            title = re.sub(r"^\W+", "", b["title"]).rstrip(":")  # their title opens with an emoji
            if b["toc"]:
                toc = [x for x in b["toc"] if x["href"] != "#"]
                inner = "<p>%s</p>" % b["html"]
                if minimal:  # their contents box sits inside the summary, closed
                    inner += """
            <details class="gp-btoc gp-btoc--inline">
              <summary>%s</summary>
              <ol>%s</ol>
            </details>""" % (esc(b["tocTitle"]), "".join('<li><a href="%s">%s</a></li>' % (esc(x["href"]), esc(x["label"])) for x in toc))
                out.append('          <aside class="gp-bbox gp-bbox--summary" aria-label="%s">\n            <p class="gp-bbox__title">%s</p>\n            %s\n          </aside>' % (esc(title), esc(title), inner))
            elif b["links"] and len(b["links"]) > 1:
                links = "".join('<a class="gp-bchip" href="%s">%s</a>' % (esc(local(l["href"], minimal)), esc(l["label"])) for l in b["links"])
                out.append('          <aside class="gp-bbox" aria-label="%s">\n            <p class="gp-bbox__title">%s</p>\n            <p class="gp-bbox__chips">%s</p>\n          </aside>' % (esc(title), esc(title), links))
            else:
                h = b["html"]
                for href in re.findall(r'href="([^"]+)"', h):
                    h = h.replace('href="%s"' % href, 'href="%s"' % esc(local(html.unescape(href), minimal)))
                out.append('          <aside class="gp-bbox" aria-label="%s">\n            <p class="gp-bbox__title">%s</p>\n            <p>%s</p>\n          </aside>' % (esc(title), esc(title), h))
        elif t == "ad":
            c1, c2 = b["cards"]
            out.append("""          <!-- Their in-article banner (inline-styled on live), on the set's parts. -->
          <aside class="gp-bad" aria-label="%s">
            <div>
              <span class="gp-bad__badge">%s</span>
              <p class="gp-bad__head">%s <span>%s</span></p>
              <p class="gp-bad__sub">%s</p>
              <a class="gp-btn gp-btn--primary" href="%s">%s <span aria-hidden="true">&nearr;</span></a>
            </div>
            <dl class="gp-bad__stats">
              <div><img src="../assets/img/blog/coin-icon.png" alt="" width="36" height="36"><dt>%s</dt><dd>%s</dd></div>
              <div><img src="../assets/img/blog/graph-icon.png" alt="" width="36" height="36"><dt>%s</dt><dd>%s</dd></div>
            </dl>
          </aside>""" % (esc(b["badge"]), esc(b["badge"]), esc(b["head"]), esc(b["accent"]), esc(b["sub"]),
                         esc(local(b["cta"][0]["href"], minimal)), esc(b["cta"][0]["label"]),
                         esc(c1["lines"][1]), esc(c1["lines"][0]), esc(c2["lines"][1]), esc(c2["lines"][0])))
        elif t == "author":
            name_line, bio = b["text"][0], b["text"][1]
            name, cred = person(name_line)
            li, allp = b["links"][0], b["links"][1]
            out.append("""          <section class="gp-bauthor" id="About_GoldenPi_Expert" aria-labelledby="author-title">
            <img class="gp-bauthor__photo" src="../assets/img/blog/%s.jpg" alt="%s" width="120" height="120" loading="lazy">
            <div>
              <h2 class="gp-bauthor__kicker" id="author-title">%s</h2>
              <p class="gp-bauthor__name">%s <span>%s</span></p>
              <p class="gp-bauthor__bio">%s</p>
              <p class="gp-bauthor__links"><a class="gp-btn gp-btn--ghost gp-btn--sm" href="%s">%s</a>
                <a class="gp-bauthor__in" href="%s" rel="noopener" target="_blank">LinkedIn<span class="sr-only"> profile of %s</span></a></p>
            </div>
          </section>""" % (img_base(b["photo"]), esc(name), esc(b["kicker"]), esc(name), esc(cred), esc(bio),
                           esc(allp["href"]), esc(allp["label"]), esc(li["href"]), esc(name)))
    return "\n".join(out), toc


SHARE = [
    ("Facebook", "https://www.facebook.com/sharer/sharer.php?u=" + POST_URL),
    ("Twitter", "https://x.com/intent/tweet?text=Check%20out%20this%20article:%20HDFC%20Bank%20Fixed%20Deposits%20%28FDs%29%20and%20Interest%20Rates%20for%20October%202026%20-%20" + POST_URL),
    ("Linkedin", "https://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fgoldenpi.com%2Fblog%2Ffixed-deposit%2Fhdfc-bank-fixed-deposits-fds-and-interest-rates%2F&title=HDFC%20Bank%20Fixed%20Deposits%20%28FDs%29%20and%20Interest%20Rates%20for%20October%202026"),
    ("Whatsapp", "https://api.whatsapp.com/send?text=HDFC%20Bank%20Fixed%20Deposits%20%28FDs%29%20and%20Interest%20Rates%20for%20October%202026%20%0A%0A%20https%3A%2F%2Fgoldenpi.com%2Fblog%2Ffixed-deposit%2Fhdfc-bank-fixed-deposits-fds-and-interest-rates%2F"),
]


def share():
    return '          <nav class="gp-bshare" aria-label="Share this article">%s</nav>' % "".join(
        '<a href="%s" target="_blank" rel="noreferrer">%s</a>' % (esc(h), l) for l, h in SHARE)


def sidebar(minimal, toc):
    out = []
    if toc and not minimal:
        out.append("""        <nav class="gp-btoc" aria-labelledby="toc-title">
          <p class="gp-btoc__title" id="toc-title">Table of Contents</p>
          <ol>%s</ol>
        </nav>""" % "".join('<li><a href="%s">%s</a></li>' % (esc(x["href"]), esc(x["label"])) for x in toc))
    for w in POST["sidebar"]:
        if w["items"] and "date" in w["items"][0]:
            items = "".join('<li><a href="%s">%s</a><time>%s</time></li>' % (esc(local(i["href"], minimal)), esc(i["title"]), esc(i["date"])) for i in w["items"])
            out.append('        <section class="gp-bwidget"><h2 class="gp-bwidget__title">%s</h2><ul class="gp-bwidget__news" role="list">%s</ul></section>' % (esc(w["title"]), items))
        else:
            items = "".join('<li><a href="%s">%s</a></li>' % (esc(local(i["href"], minimal)), esc(i["title"])) for i in w["items"])
            out.append('        <section class="gp-bwidget"><h2 class="gp-bwidget__title">%s</h2><ul class="gp-bwidget__links" role="list">%s</ul></section>' % (esc(w["title"]), items))
    return "\n".join(out)


def related(minimal):
    items = "\n".join("""          <li><a class="gp-bcard__link" href="%s">
            <span class="gp-bthumb%s">%s</span>
            <span class="gp-bcard__title">%s</span>
            <time class="gp-bmeta">%s</time>
          </a></li>""" % (esc(local(r["href"], minimal)), "" if minimal else " gp-bthumb--tint", pic(r["img"]), esc(r["title"]), esc(r["date"])) for r in POST["related"])
    return """  <section class="gp-section gp-section--tight" aria-labelledby="related-title">
    <div class="gp-shell">
      <h2 class="gp-bsec__title%s" id="related-title">Related Posts</h2>
      <ul class="gp-brelated%s" role="list">
%s
      </ul>
    </div>
  </section>
""" % (" gp-bsec__title--rule" if minimal else "", " gp-brelated--grid" if minimal else "", items)


def comment():
    c = POST["comment"]
    return """      <section class="gp-bcomment" aria-labelledby="comment-title">
        <h2 class="gp-bsec__title" id="comment-title">Leave a Comment</h2>
        <form action="#" onsubmit="return false">
          <label for="c-comment">Comment <span aria-hidden="true">*</span></label>
          <textarea id="c-comment" name="comment" rows="5" required></textarea>
          <div class="gp-bcomment__row">
            <div><label for="c-name">Name <span aria-hidden="true">*</span></label><input id="c-name" name="author" autocomplete="name" required></div>
            <div><label for="c-email">Email <span aria-hidden="true">*</span></label><input id="c-email" name="email" type="email" autocomplete="email" required></div>
            <div><label for="c-url">Website</label><input id="c-url" name="url" type="url" autocomplete="url"></div>
          </div>
          <label class="gp-bcomment__check"><input type="checkbox" name="wp-comment-cookies-consent"> %s</label>
          <button class="gp-btn gp-btn--primary" type="submit">%s</button>
        </form>
      </section>""" % (esc(c["labels"][4]), esc(c["submit"]))


def post_page(minimal):
    blocks, toc = article_blocks(minimal)
    name, cred = person(POST["author"])
    views = re.search(r"(\d+ views)", POST["byline"]).group(1)
    slide = LANDING["slides"][0]
    prev = POST["prev"]
    crumb = crumbs([("Home", "blog%s.html" % ("-minimal" if minimal else "")),
                    (POST["crumbs"][1]["label"], POST["crumbs"][1]["href"]), (POST["h1"], "")])
    hero_img = pic(POST["heroImg"], "HDFC Bank Fixed Deposits (FDs) and Interest Rates. Trusted Bank, Competitive Interest Rates, Flexible Tenures.", eager=True, sizes="(min-width: 1200px) 1160px, 100vw")
    byline = """<p class="gp-bmeta gp-bmeta--byline">written by <a href="%s">%s</a><span class="gp-bmeta__cred"> | %s</span><span class="gp-bmeta__sep" aria-hidden="true"></span><time datetime="2026-10-03">%s</time><span class="gp-bmeta__sep" aria-hidden="true"></span><!-- DATA: view count as captured -->%s</p>""" % (
        esc(POST["authorHref"]), esc(name), esc(cred), esc(POST["date"]), views)
    if minimal:
        head = """  <section class="gp-section gp-section--tight">
    <div class="gp-shell">
%s
      <div class="gp-bpost gp-bpost--minimal">
        <article class="gp-barticle">
          <figure class="gp-bpost__img">%s</figure>
          <h1 class="gp-bpost__title gp-bpost__title--center">%s</h1>
          %s
""" % (crumb, hero_img, esc(POST["h1"]), byline)
    else:
        head = """  <section class="gp-bhero gp-bhero--post">
    <div class="gp-shell">
%s
      <header class="gp-bpost__head">
        <p class="gp-bcats">%s</p>
        <h1 class="gp-bpost__title">%s</h1>
        %s
      </header>
    </div>
  </section>
  <section class="gp-section gp-section--tight gp-section--flush-top">
    <div class="gp-shell">
      <div class="gp-bpost">
        <article class="gp-barticle">
          <figure class="gp-bpost__img gp-bpost__img--framed">%s</figure>
""" % (crumb, cats(slide["cats"], False), esc(POST["h1"]), byline, hero_img)
    body = head + blocks + """
%s
          <a class="gp-bprev" href="%s"><span>%s</span>%s</a>
%s
        </article>
        <aside class="gp-bside" aria-label="More from the blog">
%s
        </aside>
      </div>
    </div>
  </section>
%s%s""" % (share(), esc(local(prev["href"], minimal)), esc(prev["label"].capitalize()), esc(prev["title"]),
             comment() if minimal else "", sidebar(minimal, toc), related(minimal),
             "" if minimal else '  <div class="gp-shell gp-bcomment-wrap">\n%s\n  </div>\n' % comment())
    body = "  <!-- DATA: goldenpi.com%s captured %s. Article body, table, sidebar and related posts read from the capture. -->\n" % (
        POST_URL.replace("https://goldenpi.com", ""), SNAPSHOT) + body + NEWS
    page("blog-post%s" % ("-minimal" if minimal else ""), POST["title"], POST["h1"],
         ("Blog article, minimal: the live layout on the set's schema." if minimal else
          "Blog article, redesigned: reading column, contents rail, the blog's navy as the reading colour."),
         body, "" if minimal else SPY_JS)


if __name__ == "__main__":
    landing_full()
    landing_minimal()
    post_page(False)
    post_page(True)
