#!/usr/bin/env python3
"""footer-ggn-prelogin-bonds.html: footer-ggn-prelogin-home.html (index.html's
footer, black / white / gold) with its SEO part swapped for footer-bonds.html's:
the corporate bonds guide and its Collections, instead of the About GoldenPi
Q&As, and without the fold's legal block (Note to Investors, Investor
Education, SMARTODR, Risk Disclosure). Everything else is the home footer.

Both sources are read at build time, so edits to either carry over. The guide's
own CSS comes across from footer-bonds' inline styles, its table on the black
scheme's card tone instead of white.

    python3 pages/_convert.py && python3 pages/_build.py && python3 pages/_footer_ggn.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
HOME = os.path.join(HERE, "footer-ggn-prelogin-home.html")
BONDS = os.path.join(HERE, "footer-bonds.html")
OUT = os.path.join(HERE, "footer-ggn-prelogin-bonds.html")
PART2 = "  <!-- Part 2: SEO copy and SEO links"


def part2(h, end):
    """The Part 2 block: its comment through the last </div> before `end`."""
    i = h.index(PART2)
    j = h.rindex("    </div>\n  </div>\n", i, h.index(end, i)) + len("    </div>\n  </div>\n")
    return i, j


def main():
    home = open(HOME, encoding="utf-8").read()
    bonds = open(BONDS, encoding="utf-8").read()
    a, b = part2(home, "  </details>\n</footer>")
    c, d = part2(bonds, "</footer>")
    seo = bonds[c:d]
    if 'class="ft-guide"' not in seo:
        raise SystemExit("footer-ggn-prelogin-bonds: footer-bonds' guide not found in its Part 2")
    page = home[:a] + seo + home[b:]
    # The fold opens straight onto the SEO part: the home footer's Note to
    # Investors, Investor Education, SMARTODR and Risk Disclosure block is
    # left out here (user, 2026-10-07).
    f = page.index("    </summary>\n", page.index('<details class="ft-fold">')) + len("    </summary>\n")
    g = page.index(PART2, f)
    if "Note to Investors" not in page[f:g]:
        raise SystemExit("footer-ggn-prelogin-bonds: fold's legal block not where expected")
    page = page[:f] + "\n" + page[g:]

    css = re.search(r"  /\* Corporate bonds guide.*?(?=</style>)", bonds, re.S).group(0)
    css = css.replace("border-radius: 12px; background: #fff; }", "border-radius: 12px; background: var(--ft-card); }")
    page = page.replace("</head>", "<style>\n%s</style>\n</head>" % css, 1)
    page = re.sub(r"<title>.*?</title>", "<title>Footer, pre-login bonds | GoldenPi</title>", page, count=1, flags=re.S)
    page = page.replace("<h1 class=\"sr-only\">GoldenPi footer, pre-login home</h1>",
                        "<h1 class=\"sr-only\">GoldenPi footer, pre-login bonds</h1>", 1)
    page = page.replace("<!-- index.html's footer, black scheme. Generated by pages/_convert.py; do not edit. -->",
                        "<!-- footer-ggn-prelogin-home.html with footer-bonds.html's SEO part. Generated by "
                        "pages/_footer_ggn.py; do not edit. -->", 1)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(page)
    print("%s  %d bytes" % (os.path.relpath(OUT, os.path.dirname(HERE)), len(page)))


if __name__ == "__main__":
    main()
