#!/usr/bin/env python3
"""Write the four pages captured from production (goldenpi.com, 2026-09-28):

    media.html, sovereign-gold-bond.html, government-securities.html,
    bond-better-return-fds.html

UAT only serves a placeholder at these paths, so the source is production:
crawl/rendered/prod_<slug>.html, plus crawl/rendered/prod_interact.json for what
needs interaction (every media card behind SEE MORE, tooltip text). Copy that
repeats or runs long (FAQ answers, reviews, blog cards, media cards) is read
straight out of the capture here rather than retyped, so it cannot drift.
Short headline copy is typed below, verbatim from content/prod_<slug>.md.

The promo bar, header and footer are lifted from corporate-bonds.html, as
_build.py does. Page CSS is the PRODUCT PAGES block at the end of final.css.

    python3 pages/_prod.py && python3 pages/_build.py
"""
import html
import json
import os
import re
import urllib.parse

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RENDERED = os.path.join(ROOT, "crawl", "rendered")
SNAPSHOT = "2026-09-28"
esc = html.escape


def capture(slug):
    return open(os.path.join(RENDERED, "prod_%s.html" % slug), encoding="utf-8").read()


# Captured URL -> local file name, as crawl/images.py saved it.
IMG = dict(r.split("\t", 1) for r in open(os.path.join(ROOT, "assets", "img-map.tsv"), encoding="utf-8").read().splitlines() if "\t" in r)
local = lambda url: IMG[urllib.parse.unquote(html.unescape(url))]

INTERACT = json.load(open(os.path.join(RENDERED, "prod_interact.json"), encoding="utf-8"))


def tip(slug, label):
    """Tooltip text as captured by hovering the info icon beside `label`."""
    for t in INTERACT[slug]["tooltips"]:
        if t["label"] == label:
            return t["tip"][0]
    raise KeyError(label)


# ---------------------------------------------------------------- shell

REF = open(os.path.join(HERE, "corporate-bonds.html"), encoding="utf-8").read()
SHELL = REF[REF.index('<a class="gp-skip"'):REF.index('<main id="main-content">')]
SHELL = SHELL.replace(' aria-current="page"', "")
SHELL = re.sub(r"header-nav-(bonds|fd)-selected\.svg", r"header-nav-\1.svg", SHELL)
FOOTER = REF[REF.index("<!-- ============================================================== footer -->"):]
FOOTER = FOOTER[:FOOTER.index("</footer>") + len("</footer>")]

HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<!-- {note}
     Generated by pages/_prod.py from crawl/rendered/prod_{slug}.html
     (goldenpi.com, captured {snap}); copy in content/prod_{slug}.md. -->
<meta name="description" content="{desc}">
<meta property="og:type" content="website">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<link rel="icon" href="../assets/img/goldenpi-logo.svg">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://api.fontshare.com/v2/css?f[]=satoshi@400,500,700,900&display=swap">
<link rel="stylesheet" href="../assets/site.css">
<link rel="stylesheet" href="../assets/final.css">
<script src="https://cdn.tailwindcss.com"></script>
<script>
  tailwind.config = {{
    theme: {{
      extend: {{
        colors: {{
          gold: "#d4af37", ink: "#322811", page: "#f7f5f2", subtext: "#666666",
          stroke: "#e7e3d9", deep: "#1a1510", bronze: "#8a6520", gain: "#06963c",
        }},
        fontFamily: {{
          sans: ['"Satoshi"', "ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
        }},
      }},
    }},
  }};
</script>
</head>
<body class="gp-prod">

"""

SCRIPTS = """
<script>
// Scroll reveal. The .reveal-ready class is added by script, so if this never
// runs the content simply stays visible rather than staying hidden.
(function () {
  if (!('IntersectionObserver' in window)) return;
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  document.documentElement.classList.add('reveal-ready');
  var io = new IntersectionObserver(function (entries) {
    entries.forEach(function (e) {
      if (!e.isIntersecting) return;
      e.target.classList.add('is-in');
      io.unobserve(e.target);
    });
  }, { rootMargin: '0px 0px -8% 0px', threshold: 0.04 });
  document.querySelectorAll('[data-reveal]').forEach(function (el) { io.observe(el); });
})();
// Figures count up the first time they are seen. The true value is already in
// the markup and is what the count ends on; data-sep keeps Indian grouping.
(function () {
  if (!('IntersectionObserver' in window)) return;
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  var fmt = function (n, sep) { return sep ? n.toLocaleString('en-IN') : String(n); };
  var io = new IntersectionObserver(function (entries) {
    entries.forEach(function (e) {
      if (!e.isIntersecting) return;
      io.unobserve(e.target);
      var el = e.target, sep = el.hasAttribute('data-sep');
      var target = Number(el.textContent.replace(/,/g, '')), t0 = null;
      function step(ts) {
        if (!t0) t0 = ts;
        var p = Math.min((ts - t0) / 1200, 1);
        el.textContent = fmt(Math.round(target * (1 - Math.pow(1 - p, 3))), sep);
        if (p < 1) requestAnimationFrame(step);
      }
      requestAnimationFrame(step);
    });
  }, { threshold: 0.6 });
  document.querySelectorAll('[data-count]').forEach(function (el) { io.observe(el); });
})();
// Video buttons open their <dialog> through invoker commands (commandfor).
// Where the browser lacks them, do the same by hand. Closing stops the video.
(function () {
  if (!('command' in HTMLButtonElement.prototype)) {
    document.querySelectorAll('[commandfor]').forEach(function (b) {
      b.addEventListener('click', function () {
        var d = document.getElementById(b.getAttribute('commandfor'));
        if (b.getAttribute('command') === 'close') d.close(); else d.showModal();
      });
    });
  }
  document.querySelectorAll('.gp-video-dialog').forEach(function (d) {
    d.addEventListener('click', function (e) { if (e.target === d) d.close(); });
    d.addEventListener('close', function () { var v = d.querySelector('video'); if (v) v.pause(); });
  });
})();
</script>
"""


def page(slug, title, desc, note, body, extra_js=""):
    out = HEAD.format(title=esc(title), desc=esc(desc), note=note, slug=slug, snap=SNAPSHOT)
    out += SHELL + '<main id="main-content">\n' + body + "\n</main>\n\n" + FOOTER + "\n" + SCRIPTS + extra_js
    out += "\n</body>\n</html>\n"
    open(os.path.join(HERE, slug + ".html"), "w", encoding="utf-8").write(out)
    print("wrote pages/%s.html" % slug)


# ------------------------------------------------------ shared sections

#
# Every section is built from the parts corporate-bonds.html uses: its hero
# grid, gp-section heads, gp-block cards, gp-stats, gp-steps, gp-reviews,
# gp-blogcard and the FAQ + Need Help layout; the FD page's partner strip,
# comparison table and cream panel. The few page-only parts (tooltips, FD
# bars, video cards, press cards) are the PRODUCT PAGES block in final.css.

SECTION = '<section data-reveal class="gp-section gp-section--tight gp-section--flush-top"%s>'


def section(inner, sid=""):
    return "  %s\n    <div class=\"gp-shell\">\n%s\n    </div>\n  </section>\n" % (
        SECTION % (' id="%s"' % sid if sid else ""), inner)


def breadcrumb(label):
    return """      <nav class="t-small t-muted mb-6" aria-label="Breadcrumb">
        <a href="index.html" class="hover:text-ink">Home</a>
        <span class="mx-1.5">&rsaquo;</span>
        <span class="text-ink font-medium">%s</span>
      </nav>""" % label


def hero(crumb, copy, art):
    """corporate-bonds' hero: copy left, art right, on the gp-hero wash."""
    return """  <!-- ============================================================== hero -->
  <section class="gp-hero">
    <div class="gp-shell pt-6 pb-2">
%s
      <div class="grid gap-8 md:grid-cols-[1.05fr_0.95fr] md:items-center">
        <div data-reveal>
%s
        </div>
%s
      </div>
    </div>
  </section>
""" % (breadcrumb(crumb) if crumb else "", copy, art)


def head(title):
    return """      <div class="gp-section__head gp-section__head--marked">
        <h2 class="gp-section__title">%s</h2>
      </div>""" % title


def info(text, label):
    """Their info icon; hover or focus shows the text the live page shows."""
    return ('<span class="gp-tip"><button type="button" class="gp-tip__btn" aria-label="What is %s?">'
            '<img src="../assets/img/info.svg" alt="" width="14" height="14"></button>'
            '<span class="gp-tip__text" role="tooltip">%s</span></span>') % (esc(label), esc(text))


def chips(slug, terms):
    """corporate-bonds' "What it means?" chips, each with its captured definition."""
    return """        <div class="mt-6 flex flex-wrap items-center gap-2 t-small">
          <span class="font-semibold">What it means?</span>
          %s
        </div>""" % "\n          ".join(
        '<span class="inline-flex items-center gap-1 rounded-full border border-stroke bg-white py-1 pl-3 pr-1.5">%s %s</span>'
        % (t, info(tip(slug, t), t)) for t in terms)


def blocks(items, cols="sm:grid-cols-2 lg:grid-cols-4"):
    """gp-block cards: icon squircle, title, description."""
    out = []
    for icon, title, desc in items:
        out.append("""        <div class="gp-block">
          <span class="gp-block__icon"><img src="../assets/img/%s" alt=""></span>
          <h3 class="gp-block__title">%s</h3>
          %s
        </div>""" % (icon, title, '<p class="gp-block__desc">%s</p>' % desc if desc else ""))
    return '      <div class="grid gap-4 gp-stagger %s" data-reveal>\n%s\n      </div>' % (cols, "\n".join(out))


def steps(items):
    lis = "\n".join("""        <li>
          <p class="gp-steps__num"><span>%02d</span></p>
          <p class="gp-steps__title">%s</p>
        </li>""" % (n, t) for n, t in enumerate(items, 1))
    return '      <ol class="gp-steps">\n%s\n      </ol>' % lis


def notify(img, heading, sub, alt):
    """Their empty state. Notify Me is a button on the live site (it opens
    sign-up), so it stays one."""
    return """      <div class="gp-card mx-auto flex max-w-2xl flex-col items-center gap-6 p-6 text-center sm:flex-row sm:p-8 sm:text-left">
        <img src="../assets/img/%s" alt="%s" width="150" height="130" class="w-32 flex-none sm:w-36">
        <div>
          <h2 class="t-h3 font-bold">%s</h2>
          <p class="mt-1 t-small t-muted">%s</p>
          <button type="button" class="gp-cta gp-cta--primary gp-cta--sm mt-4">Notify Me</button>
        </div>
      </div>""" % (img, alt, heading, sub)


def partners(label):
    """fixed-deposits' partner strip."""
    return """      <div class="flex flex-col items-center gap-6 rounded-2xl border border-stroke bg-white px-6 py-7 sm:flex-row sm:gap-10">
        %s
        <div class="flex flex-1 flex-wrap items-center justify-center gap-x-10 gap-y-5 sm:justify-between">
          <img src="../assets/img/AxisSecurities.png" alt="Axis Securities" height="26" class="h-6 w-auto object-contain">
          <img src="../assets/img/AnandRathi.webp" alt="Anand Rathi" height="26" class="h-6 w-auto object-contain">
          <img src="../assets/img/Sakthi-Finance-logo.png" alt="Sakthi Finance" height="26" class="h-6 w-auto object-contain">
          <img src="../assets/img/centrum.png" alt="Centrum" height="26" class="h-6 w-auto object-contain">
        </div>
      </div>""" % ('<p class="flex-none t-small font-semibold t-muted">%s</p>' % label if label else "")


def milestones():
    """The live Milestones band as corporate-bonds' stat strip."""
    return section("""      <p class="gp-divider">Milestones</p>
      <dl class="gp-stats">
        <div class="gp-stats__item">
          <dd class="gp-stats__value"><span data-count>18</span> Lac+</dd>
          <dt class="gp-stats__label">registered users &amp; growing</dt>
        </div>
        <div class="gp-stats__item">
          <dd class="gp-stats__value">&#8377;<span data-count>3000</span> Cr+</dd>
          <dt class="gp-stats__label">worth of bonds available on the platform everyday</dt>
        </div>
        <div class="gp-stats__item">
          <dd class="gp-stats__value">&#8377;<span data-count>6300</span> Cr+</dd>
          <dt class="gp-stats__label">total transaction through our platform</dt>
        </div>
      </dl>""")


def reviews(slug):
    """The five Google reviews, verbatim from the capture, in corporate-bonds'
    drifting row."""
    h = capture(slug)
    i = h.index("<happy-users")
    seg = h[i:h.index("</happy-users>", i)]
    cards = re.findall(r'<img class="user-img" alt="[^"]*" src="[^"]*/([^"/]+)">.*?'
                       r'<span class="user-name">(.*?)</span>.*?<span class="feedback-txt">(.*?)</span>', seg, re.S)
    seen, rows = set(), []
    for img, name, text in cards:
        name = html.unescape(name).strip()
        if name in seen:
            continue
        seen.add(name)
        rows.append((name, img, re.sub(r"\s+", " ", html.unescape(re.sub("<[^>]+>", "", text))).strip()))
    if len(rows) != 5:
        raise SystemExit("reviews: expected 5 in %s, found %d" % (slug, len(rows)))

    def fig(r, hidden=False):
        name, img, text = r
        return """          <figure class="gp-review"%s>
            <figcaption class="gp-review__head">
              <img class="gp-review__avatar gp-review__avatar--photo" src="../assets/img/%s" alt="" width="56" height="56" loading="lazy">
              <span>
                <span class="gp-review__name">%s</span>
                <span class="gp-review__stars" aria-label="5 out of 5 stars">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
              </span>
            </figcaption>
            <blockquote class="gp-review__text">%s</blockquote>
          </figure>""" % (' aria-hidden="true"' if hidden else "", img, esc(name), esc(text))

    link = re.search(r'href="([^"]+)"[^>]*>Read all Reviews', seg).group(1)
    return section("""%s

      <!-- DATA: Google reviews, as production shows them on %s. -->
      <div class="gp-reviews">
        <div class="gp-reviews__track" style="--n:5">
%s
%s
        </div>
      </div>

      <div class="mt-5 text-center">
        <a class="t-small font-bold t-bronze underline" href="%s">Read all Reviews</a>
      </div>""" % (head("Why 15 Lakh+ Users Trust GoldenPi for Bond Investing"), SNAPSHOT,
                   "\n".join(fig(r) for r in rows), "\n".join(fig(r, True) for r in rows), link))


def blogs(slug, title):
    h = capture(slug)
    i = h.index(title)
    seg = h[i:h.index('class="blog-footer"', i)]
    cards = re.findall(r'<a class="each-blog[^"]*" href="([^"]+)">.*?url\(&quot;([^&]+)&quot;\).*?'
                       r'<p class="secondary-txt">(.*?)</p>.*?<p class="primary-txt"[^>]*>(.*?)</p>', seg, re.S)
    out = []
    for href, img, meta, t in cards:
        date, _, cat = html.unescape(meta).strip().partition(" | ")
        out.append("""        <a class="gp-blogcard" href="%s">
          <span class="gp-blogcard__body">
            <span class="gp-blogcard__cat">%s</span>
            <span class="gp-blogcard__title">%s</span>
            <span class="gp-blogcard__meta">%s</span>
            <span class="gp-blogcard__more">Read more
              <img src="../assets/img/SVG-1.png" alt="" width="14" height="14"></span>
          </span>
          <img class="gp-blogcard__media gp-blogcard__media--photo" src="../assets/img/%s" alt="" width="380" height="280">
        </a>""" % (href, esc(cat), esc(html.unescape(t).strip()), esc(date), local(img)))
    return section("""%s

      <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
%s
      </div>

      <div class="mt-6 text-center">
        <a class="t-small font-bold t-bronze underline" href="https://goldenpi.com/blog">View all Blogs</a>
      </div>""" % (head(title), "\n".join(out)))


def faq_from_capture(slug):
    h = capture(slug)
    qa = re.findall(r'<h3 class="header-title[^"]*"[^>]*>(.*?)</h3>.*?<div class="desc[^"]*">(.*?)</div>', h, re.S)
    out = []
    for q, a in qa:
        a = a.replace("<!---->", "").strip()
        paras = [p.strip() for p in re.split(r"(?:<br>\s*){2,}", a) if p.strip()]
        out.append((html.unescape(q).strip(),
                    "".join("<p>%s</p>" % p.replace("<a href=", '<a class="underline" href=') for p in paras)))
    return out


def faq(title, items):
    rows = "\n".join("""          <details class="gp-faq__item"%s>
            <summary class="gp-faq__q">%s</summary>
            <div class="gp-faq__a">%s</div>
          </details>""" % (" open" if n == 0 else "", esc(q), a) for n, (q, a) in enumerate(items))
    return section("""%s

      <div class="gp-faq-layout">
        <div class="gp-faq">
%s
        </div>
        <!-- Not on the live page: the support card fixed-deposits carries. -->
        <aside class="gp-need-help">
          <img class="gp-need-help__image" src="../assets/img/support-icon.svg" alt="" width="237" height="237">
          <p class="gp-need-help__title">
            <img src="../assets/img/phone-icon.svg" alt="" width="20" height="20">
            Need Help
          </p>
          <p class="gp-need-help__desc">Talk to our Support Team for free. We will
            help you through your investment journey.</p>
          <a class="gp-cta gp-cta--primary" href="contact-us.html">
            Contact Us
            <img class="gp-cta__arrow" src="../assets/img/arrow-right.svg" alt="" width="16" height="16">
          </a>
        </aside>
      </div>""" % (head(title), rows))


def hero_img(src, w, h, alt):
    return """        <img src="../assets/img/%s" width="%d" height="%d"
             class="w-full max-w-[520px] justify-self-center"
             alt="%s">""" % (src, w, h, alt)


def how_to(title, items):
    """Their process animation beside the steps, which read top to bottom."""
    return section("""%s

      <div class="gp-howto grid items-center gap-6 md:grid-cols-[0.85fr_1.15fr] md:gap-10">
        <div class="gp-howto__art">
          <img src="../assets/img/investment-process.gif" alt="" width="420" height="420" loading="lazy">
        </div>
%s
      </div>""" % (head(title), steps(items).replace('class="gp-steps"', 'class="gp-steps gp-steps--stack" data-reveal')))


# ================================================================ SGB

def sgb():
    s = "sovereign-gold-bond"
    tick = '<img src="../assets/img/tick-sgb.svg" alt="Yes" width="17" height="16" class="inline-block">'
    cross = '<img src="../assets/img/close-sgb.svg" alt="No" width="17" height="16" class="inline-block">'
    rows = [("2.5% P.A Interest on Amount", (1, 0, 0)), ("Stored in Digital Form", (1, 1, 0)),
            ("Liquidity in Market", (1, 1, 0)), ("0% capital gain tax", (1, 0, 0)), ("Purity", (1, 1, 0))]
    trs = "\n".join("""            <tr>
              <th scope="row" class="p-4 text-left font-bold"><span class="inline-flex items-center gap-1">%s %s</span></th>
              %s
            </tr>""" % (esc(r), info(tip(s, r), r),
                        "".join('<td class="p-4 text-center%s">%s</td>' % (" gp-sgb-col" if i == 0 else "", tick if v else cross)
                                for i, v in enumerate(vals))) for r, vals in rows)

    body = hero("Sovereign Gold Bonds", """          <h1 class="t-h1">
            <span class="t-bronze">Sovereign Gold Bonds</span><br>
            <span class="t-bronze">Online</span>
          </h1>

          <!-- DATA: open SGB series, API-driven. None on sale on %s. -->
          <div class="gp-card mt-8 flex max-w-lg items-center gap-4 p-5">
            <img src="../assets/img/sgb-no-instrument-img.svg" alt="No instrument icon" width="64" height="64" class="flex-none">
            <div>
              <p class="font-bold">No gold bonds available</p>
              <p class="t-small t-muted">Click on &#8216;Notify me&#8217; for updates on upcoming series</p>
              <button type="button" class="gp-cta gp-cta--primary gp-cta--sm mt-3">Notify Me</button>
            </div>
          </div>""" % SNAPSHOT,
        hero_img("sgb-hero-section-man-icon.png", 1266, 1168,
                 "Issued By Reserve Bank Of India. 2.5% p.a. interest extra. Discount of 50rs per gram. No capital tax gain."))

    body += """
  <!-- ============================================================ best way -->
  <!-- Their blue band, as the cream panel fixed-deposits uses for its
       cross-sell. -->
""" + section("""      <div class="gp-panel-warm rounded-3xl p-6 sm:p-10">
        <h2 class="gp-section__title text-left"><span class="gp-best">Best</span> way to Invest in Gold</h2>
        <p class="mt-3 max-w-2xl t-body t-muted">Perfect alternative to investment in physical gold, earn additional 2.5%% interest yearly on capital appreciation.</p>
        <div class="mt-8">
%s
        </div>
      </div>""" % blocks([
        ("stamp-gsec.png", "Low Investment Value", "Minimum investment starts as low as 1gm of gold."),
        ("better-returns.svg", "High Returns", "Possible Capital Appreciation + 2.5 % p.a. Assured interest"),
        ("cal.png", "Tenure", "8 Years with an option to exit in 5th, 6th &amp; 7th Year."),
        ("no-tax.png", "Tax Benefits", "Exemption from capital gain tax if held till maturity."),
    ]))

    body += section("""%s

      <div class="gp-tablewrap">
        <table class="gp-matrix w-full min-w-[520px] border-collapse t-small">
          <caption class="sr-only">Sovereign Gold Bonds compared with Gold ETF and Physical Gold</caption>
          <thead>
            <tr class="bg-[#fdf8e9] text-left">
              <th scope="col" class="p-4 font-bold">Overview %s</th>
              <th scope="col" class="p-4 text-center font-bold gp-sgb-col">SGB</th>
              <th scope="col" class="p-4 text-center font-bold">Gold ETF</th>
              <th scope="col" class="p-4 text-center font-bold">Physical Gold</th>
            </tr>
          </thead>
          <tbody class="[&>tr:not(:last-child)]:border-b [&>tr]:border-[color:var(--light-stroke)]">
%s
          </tbody>
        </table>
      </div>""" % (head('What makes Sovereign Gold Bonds (SGBs) a <span class="t-bronze">valuable investment choice</span> versus other alternatives?'),
                   info(tip(s, "Sovereign Gold Bonds"), "Sovereign Gold Bonds"), trs))

    body += section("""%s

      <!-- DATA: past SGB series, API-driven. Snapshot %s. The live row's
           download icon fetches the prospectus from a click handler with no
           URL in the markup, so it is not reproduced. -->
      <div class="gp-tablewrap">
        <table class="w-full min-w-[520px] border-collapse t-small">
          <caption class="sr-only">Previously issued Sovereign Gold Bond series</caption>
          <thead>
            <tr class="bg-[#fdf8e9] text-left">
              <th scope="col" class="p-4 font-bold">Tranche</th>
              <th scope="col" class="p-4 font-bold">End Date</th>
              <th scope="col" class="p-4 font-bold">Issue Price (&#8377; Per Gram)</th>
            </tr>
          </thead>
          <tbody class="[&>tr:not(:last-child)]:border-b [&>tr]:border-[color:var(--light-stroke)]">
            <tr>
              <th scope="row" class="p-4 text-left font-bold">Sovereign Gold Bond Scheme 2023-24 Series IV</th>
              <td class="p-4 text-subtext">16-Feb-2024</td>
              <td class="p-4 font-bold">&#8377; 6,213</td>
            </tr>
            <tr>
              <th scope="row" class="p-4 text-left font-bold">Sovereign Gold Bond Scheme 2023-24 Series III</th>
              <td class="p-4 text-subtext">22-Dec-2023</td>
              <td class="p-4 font-bold">&#8377; 6,149</td>
            </tr>
          </tbody>
        </table>
      </div>""" % (head("Previously Issued SGBs"), SNAPSHOT))

    body += how_to("How to Invest in Sovereign Gold Bond Online?",
                   ["Complete your KYC", "Enter quantity (in gms) to purchase", "Make payment to Invest"])
    body += milestones() + reviews(s) + blogs(s, "Learn about Investment in Sovereign Gold Bonds")
    body += faq("FAQs about investing in Sovereign Gold Bonds", faq_from_capture(s))
    page(s, "Sovereign Gold Bond (SGB) - Buy Online in India | GoldenPi",
         "GoldenPi is India's Trusted online platform to buy sovereign gold bonds, Debentures, and other fixed-income assets in India. To know more about online bond investment, Get started!",
         "Sovereign Gold Bonds, rebuilt from goldenpi.com/sovereign-gold-bond on corporate-bonds.html's components.",
         body)


# ============================================================== G-Sec

def gsec():
    s = "government-securities"
    body = hero("Government Securities", """          <h1 class="t-h1">
            <span class="t-bronze">Buy Government</span><br>
            <span class="t-bronze">Securities Online</span>
          </h1>

          <p class="mt-4 max-w-md t-body t-muted">
            Invest in Bonds guaranteed by The Government Of India, offering stable returns with lowest risk.
          </p>

          <!-- A button on the live site that does not navigate; here it
               jumps to the availability card. -->
          <div class="mt-8 flex flex-wrap items-center gap-4">
            <a class="gp-cta gp-cta--primary" href="#gsec-available">Explore G-Sec Bonds</a>
          </div>

          <p class="mt-8 flex items-center gap-2.5 rounded-xl border border-stroke bg-white px-4 py-3 t-small t-muted max-w-lg">
            <img src="../assets/img/ipo-hero-shield-img.png" alt="" width="18" height="18">
            <span>GoldenPi is a <span class="font-semibold t-bronze">SEBI registered Debt broker</span> and OBPP License Holder</span>
          </p>""",
        hero_img("gsec-landing.png", 1911, 1419,
                 "A Smarter Choice Than FD. Start As Low As &#8377;100. Approx 7.5% Avg. Return."))

    body += """
  <!-- ========================================================== partners -->
""" + section(partners("Trusted by leading brokers and Market leaders"))

    body += """
  <!-- DATA: G-Sec listing, API-driven. None on sale on %s. -->
""" % SNAPSHOT + section(notify("no-result-man-with-loud-speaker.svg", "Currently there are no G-Secs available",
                                "Click on &#8216;Notify Me&#8217; to receive an update.", "Gsec no result"), "gsec-available")

    body += section("""      <div class="gp-panel-warm grid gap-8 rounded-3xl p-6 sm:p-10 lg:grid-cols-[1.25fr_1fr] lg:items-center">
        <h2 class="gp-section__title gp-statement text-left">Guaranteed by the Government to repay, Government Securities (G-Secs), also known as Sovereign Bonds, allow individuals to lend money in exchange for better interest rates, lower risk, and income stability.</h2>
        <div>
%s
        </div>
      </div>""" % blocks([
        ("gsec-risk-free.png", "Risk-free", "G-Secs are guaranteed by the GOI and have no credit risk"),
        ("hassle-free-process.png", "Hassle-free Process", "Easy and secure online journey under OBPP guidelines."),
        ("gesc-no-tds.svg", "No TDS", "No tax deduction at source for interest payments received"),
    ], "gp-stack"))

    body += """
  <!-- ======================================================== explainer -->
  %s
    <div class="gp-shell grid gap-8 md:grid-cols-2 md:items-center">
      <div>
        <h2 class="gp-section__title text-left">What are Government Bonds?</h2>
        <p class="mt-4 t-body t-muted">Earn better with stable, secure, and government-backed investment bonds. G-Secs are financial instruments issued by the government to raise funds. Investing in them means lending money to the government, getting interest payments and the invested amount back later.</p>
%s
      </div>
      <div class="grid grid-cols-2 gap-4 gp-stagger" data-reveal>
        <div class="rounded-2xl bg-[#fdf8e9] p-5">
          <img src="../assets/img/money-hand-gesture.png" alt="" width="52" height="52">
          <p class="mt-3 t-body font-bold leading-snug">Regular and risk-free income</p>
        </div>
        <div class="gp-card rounded-2xl p-5">
          <img src="../assets/img/money-protection.png" alt="" width="52" height="52">
          <p class="mt-3 t-body font-bold leading-snug">Better than Bank FD</p>
        </div>
        <div class="gp-card rounded-2xl p-5">
          <img src="../assets/img/money-growth.png" alt="" width="52" height="52">
          <p class="mt-3 t-body font-bold leading-snug">Beats inflations</p>
        </div>
        <div class="rounded-2xl bg-[#fdf8e9] p-5">
          <img src="../assets/img/no-default-risk.png" alt="" width="52" height="52">
          <p class="mt-3 t-body font-bold leading-snug">No Default Risk</p>
        </div>
      </div>
    </div>
  </section>
""" % (SECTION % "", chips(s, ["G-Sec", "NBFC", "Payout"]))

    body += how_to("How to Invest in Government Bonds",
                   ["Complete your KYC", "Choose the right Government Bond", "Make payment to Invest"])
    body += milestones() + reviews(s) + blogs(s, "Learn about Investment in Government Bonds")
    body += faq("FAQs about Investment in Government Bonds", faq_from_capture(s))
    page(s, "Government Securities - Invest Online in India | GoldenPi",
         "Buy government bonds online. Government bonds are issued by the Indian government and state governments. These G-Sec Bonds are best suitable for investors with low-risk appetite and prefer safe investment",
         "Government Securities, rebuilt from goldenpi.com/government-securities on corporate-bonds.html's components.",
         body)


# ================================================== better than FDs

VIDEO_WHY = "https://s3.ap-south-1.amazonaws.com/production.goldenpi.com/static/images/01+GoldenPI+-+With+Logo+HD.mp4"
VIDEO_HOW = ("https://s3.ap-south-1.amazonaws.com/production.goldenpi.com/static/images/"
             "GoldenPi+-+How+to+Invest+in+NCD+IPO+Online+Video+Updated_1.mp4")


def video_dialog(did, label, src):
    return """  <dialog class="gp-video-dialog" id="%s" aria-label="%s" closedby="any">
    <button type="button" class="gp-video-dialog__close" commandfor="%s" command="close" aria-label="Close video">
      <img src="../assets/img/close.svg" alt="" width="20" height="20"></button>
    <video controls preload="none" src="%s"></video>
  </dialog>
""" % (did, label, did, src)


def better():
    s = "bond-better-return-fds"
    body = hero(None, """          <p class="gp-eyebrow mb-5">Apply for an IPO in just 5 minutes</p>

          <h1 class="t-h1">
            <span class="t-bronze">Get better returns</span><br>
            <span class="t-bronze">than Bank FDs</span>
          </h1>

          <ul class="mt-6 flex flex-wrap gap-2 t-small">
            <li class="rounded-full border border-stroke bg-white px-3 py-1.5 font-semibold"><span class="text-gain">&#10003;</span> No KYC required</li>
            <li class="rounded-full border border-stroke bg-white px-3 py-1.5 font-semibold"><span class="text-gain">&#10003;</span> Pay via UPI</li>
            <li class="rounded-full border border-stroke bg-white px-3 py-1.5 font-semibold"><span class="text-gain">&#10003;</span> Invest as low as 10k</li>
          </ul>

          <div class="mt-8 flex flex-wrap items-center gap-4">
            <a class="gp-cta gp-cta--primary" href="#current-ipo">View Latest IPOs</a>
            <a class="gp-textlink" href="#compare-fd">Compare with Bank FD</a>
          </div>

          <p class="mt-8 flex items-center gap-2.5 rounded-xl border border-stroke bg-white px-4 py-3 t-small t-muted max-w-lg">
            <img src="../assets/img/like.png" alt="" width="18" height="18">
            <span><span class="font-semibold t-bronze">25k+ investors</span> have invested in Rs 100cr in NCD-IPOs online</span>
          </p>""",
        hero_img("Mockup-2.png", 674, 536,
                 "A bond IPO on the GoldenPi app, with a review: &#8220;Bond IPO investing is super easy on goldenpi&#8221;, Darshan Gupta, Investor"))

    body += """
  <!-- ========================================================== compare -->
""" + section("""      <div class="grid gap-4 md:grid-cols-[1.5fr_1fr]">
        <div class="gp-card p-6 sm:p-8">
          <h2 class="gp-section__title text-left">Compare with FD</h2>
          <div class="mt-6 grid gap-6 sm:grid-cols-2 sm:items-center">
            <dl class="gp-bars" data-reveal>
              <div class="gp-bars__row" style="--w:%.0f%%">
                <dt class="gp-bars__bar">Bank Deposit</dt><dd class="gp-bars__val">6.80%% *</dd>
              </div>
              <div class="gp-bars__row gp-bars__row--bond" style="--w:100%%">
                <dt class="gp-bars__bar">Bond</dt><dd class="gp-bars__val">11.02%%</dd>
              </div>
            </dl>
            <p class="t-h3">1&nbsp;Lac Invested could earn
              <span class="gp-hero__figure">&#8377; <span data-count data-sep>21,100</span></span> more in 5 years</p>
          </div>
          <p class="mt-6 t-small t-muted">Based on pre-tax returns of high rated bonds (AA rated ) &amp; SBI Fixed deposit*</p>
        </div>
        <!-- The title "Why invest in Bonds?" is part of their thumbnail. -->
        <button type="button" class="gp-video-card" commandfor="video-why" command="show-modal">
          <img src="../assets/img/why-invest-desktop.png" alt="Why invest in Bonds? Play video" width="420" height="346">
        </button>
      </div>""" % (6.80 / 11.02 * 100), "compare-fd")

    body += """
  <!-- ====================================================== current IPO -->
""" + section("""%s

      <!-- DATA: open NCD IPO, API-driven. Snapshot %s. -->
      <article class="gp-card gp-ipo-card p-6 sm:p-8">
        <div class="flex flex-wrap items-center justify-between gap-3">
          <span class="rounded-md border border-[#06963c]/40 bg-[#e8f6ee] px-2.5 py-0.5 t-small font-bold text-gain">Open</span>
          <span class="rounded-full bg-[#fdf3d4] px-3 py-1 t-small"><b class="t-bronze">3.2%% more</b> than Bank FDs*</span>
        </div>
        <h3 class="mt-4 flex items-center gap-3 t-h3 font-bold">
          <img src="../assets/img/GPID100778.EDELWEISS-FINANCIAL-SERVICES-LIMITED.png" alt="" width="44" height="44" class="flex-none rounded-full">
          EDELWEISS FINANCIAL SERVICES LIMITED
        </h3>
        <div class="mt-6 grid gap-6 border-t border-stroke pt-6 md:grid-cols-[auto_1fr_auto] md:items-center md:gap-10">
          <p class="t-small t-muted">Earn interest<br><span class="t-h2 font-black text-gain">upto 10%% p.a.</span></p>
          <dl class="grid grid-cols-3 gap-4">
            <div><dt class="t-small t-muted">Min. Investment</dt><dd class="mt-1 font-bold">&#8377; 10,000</dd></div>
            <div><dt class="t-small t-muted">Rating</dt><dd class="mt-1"><span class="inline-block rounded-full bg-page px-2.5 py-1 t-small font-bold">A+</span></dd></div>
            <div><dt class="t-small t-muted">Issue closes</dt><dd class="mt-1 font-bold">5-Oct-2026</dd></div>
          </dl>
          <a class="gp-cta gp-cta--primary" href="https://goldenpi.com/bond-ipo/GPID100778/edelweiss-financial-services-limited">View Details</a>
        </div>
        <p class="mt-4 text-right t-small t-muted">*Compared to SBI FD rate 6.8%%</p>
      </article>""" % (head("Current IPO"), SNAPSHOT), "current-ipo")

    body += reviews(s)
    body += """  <!-- Closed IPOs is a toggle on the live page that loaded no rows on
       %s, so it is left out rather than shipped empty. -->
""" % SNAPSHOT

    body += section("""%s

      <!-- Titles are baked into their card images; the alt text carries them. -->
      <div class="grid gap-4 sm:grid-cols-3">
        <button type="button" class="gp-video-card" commandfor="video-how" command="show-modal">
          <img src="../assets/img/how-to-invest.png" alt="How to invest in NCD -IPO online? Play video" width="420" height="346" loading="lazy">
        </button>
        <a class="gp-video-card" href="https://goldenpi.com/blog/essentials/bond-market/what-are-corporate-bonds-how-to-invest/">
          <img src="../assets/img/blog2.png" alt="What are Corporate Bonds, How to invest? View more" width="314" height="278" loading="lazy">
        </a>
        <a class="gp-video-card" href="https://goldenpi.com/blog/%%20essentials/bond-market/fixed-income-securities-bonds-fds-ppf-bond-etf-which-one-to-choose/">
          <img src="../assets/img/blog1.png" alt="Fixed Income Securities: Bonds, FDs, PPF, &amp; Bond-ETF which one to choose? View more" width="314" height="278" loading="lazy">
        </a>
      </div>

      <div class="mt-10 text-center">
        <p class="t-h3 font-bold">Explore latest ongoing IPOs</p>
        <a class="mt-2 inline-block t-small font-bold t-bronze underline" href="#current-ipo">View IPOs</a>
      </div>""" % head("Learn about Bonds and NCDs"))

    ipo_steps = [("select-ipo-series-desktop.png", "Select IPO Series"),
                 ("enter-demat-upi-desktop.png", "Enter demat &amp; UPI details"),
                 ("accept-upi-mandate-desktop.png", "Accept UPI payment mandate"),
                 ("get-bond-units-desktop.png", "Get bond units in your demat account")]
    body += section("""%s

      <ol class="grid grid-cols-2 gap-4 lg:grid-cols-4">
%s
      </ol>""" % (head("How online bond IPO works?"), "\n".join("""        <li class="gp-block gp-block--stat">
          <img src="../assets/img/%s" alt="" width="72" height="72">
          <p class="gp-steps__num mb-0 border-0 pb-0"><span>%02d</span></p>
          <p class="gp-block__title">%s</p>
        </li>""" % (img, n, t) for n, (img, t) in enumerate(ipo_steps, 1))))

    body += section("""%s

      <div class="grid gap-4 lg:grid-cols-[1.35fr_1fr]">
        <div class="gp-panel-warm relative overflow-hidden rounded-3xl p-6 sm:p-8 lg:row-span-3">
          <h3 class="t-h3 font-bold max-w-md">India&#8217;s trusted online platform for bonds and debenture</h3>
          <p class="mt-2 max-w-md t-body t-muted">We are the leading bonds SaaS platform partnered with Banks and Financial Institutions</p>
          <div class="mt-6 flex flex-wrap items-center gap-x-8 gap-y-4">
            <img src="../assets/img/AxisSecurities.png" alt="Axis Securities" height="26" class="h-6 w-auto object-contain mix-blend-multiply">
            <img src="../assets/img/AnandRathi.webp" alt="Anand Rathi" height="26" class="h-6 w-auto object-contain mix-blend-multiply">
            <img src="../assets/img/Sakthi-Finance-logo.png" alt="Sakthi Finance" height="26" class="h-6 w-auto object-contain mix-blend-multiply">
            <img src="../assets/img/centrum.png" alt="Centrum" height="26" class="h-6 w-auto object-contain">
          </div>
          <img src="../assets/img/IPO_illus.png" alt="" width="337" height="322" loading="lazy" class="mt-6 ml-auto w-full max-w-[220px]">
        </div>
%s
      </div>""" % (head("We&#8217;ve simplified bond investment process"), "\n".join("""        <div class="gp-block gp-block--row">
          <img src="../assets/img/%s" alt="" width="56" height="56" loading="lazy">
          <h3 class="gp-block__title">%s</h3>
        </div>""" % c for c in [("coins-image.svg", "Enjoy a simplified investment process"),
                               ("mobile-image.png", "Go paperless and online"),
                               ("rupees-image.svg", "One stop to buy bonds and debentures")])))

    body += faq("FAQs about investment in Bond IPOs India", [
        ("What happens when I cancel my IPO application?",
         "<p>When you cancel your IPO application, all bids in the application will be canceled. However, you can apply again on or before the closing date. If you cancel the IPO application after funds are blocked by ASBA, your fund will be released within 48 hours of the allotment. In case the fund is not released, kindly contact the registrar of the NCD IPO issue for guidance.</p>"),
        ("When will I get the money back if I cancel?",
         '<p>When you cancel the IPO application after funds are blocked by ASBA, your fund will be released within 48 hours of the allotment. In case the fund is not released, you can write to <a class="underline" href="mailto:contact-us@goldenpi.com">contact-us@goldenpi.com</a> for guidance.</p>'),
    ])
    body += video_dialog("video-why", "Why invest in Bonds?", VIDEO_WHY)
    body += video_dialog("video-how", "How to invest in NCD-IPO online?", VIDEO_HOW)
    page(s, "Better Than Fixed Deposits | Invest in Bonds Via GoldenPi",
         "NCDs offer better returns than bank FDs. Get upto 11% fixed monthly returns in the bond market with GoldenPi. ✓50k+ Investors. ✓No KYC required. ✓Pay via UPI. ✓Invest as low as 10k.",
         "Better than FDs, rebuilt from goldenpi.com/bond-better-return-fds on corporate-bonds.html's components.",
         body)


# ============================================================== media

def media():
    cards = INTERACT["media"]["cards"]
    groups = {}
    for c in cards:
        title, desc, source = c["texts"]
        year = re.search(r"(\d{4})\s*$", source).group(1)
        groups.setdefault(year, []).append((title, desc, source, c["href"], local(c["img"])))

    def split(src):
        m = re.match(r"^(.*?),\s*(\w+\.? \d{1,2}, \d{4})\s*$", src)
        return (m.group(1).strip(), m.group(2)) if m else (src, "")

    def card(t, d, src, href, img):
        """Their live media card in the set's schema: title, summary and
        "Publication, date" on the left, the story's photo square on the right."""
        pub, when = split(src)
        return """            <a class="gp-presscard" href="%s" target="_blank" rel="noopener">
              <span class="gp-presscard__body">
                <span class="gp-presscard__title">%s</span>
                <span class="gp-presscard__desc">%s</span>
                <span class="gp-presscard__source"><b>%s</b>%s</span>
              </span>
              <span class="gp-presscard__frame"><img src="../assets/img/%s" alt="" width="160" height="160" loading="lazy"></span>
            </a>""" % (esc(href), esc(t), esc(d), esc(pub), (", " + esc(when)) if when else "", img)

    years = sorted(groups, reverse=True)
    body = hero("Media", """          <h1 class="t-h1"><span class="t-bronze">Media Coverage</span></h1>""", "")

    tabs = "\n".join("""            <button type="button" class="gp-tab" role="tab" id="tab-y%s"
                    aria-controls="panel-y%s" aria-selected="%s"%s>%s</button>""" % (
        y, y, "true" if n == 0 else "false", "" if n == 0 else ' tabindex="-1"', y) for n, y in enumerate(years))
    panels = []
    for n, y in enumerate(years):
        items = groups[y]
        # Nine fill three rows of three; a short year shows the most it can
        # without leaving a row part-empty. The rest sit behind their own
        # SEE MORE, as the live page pages them.
        shown = 9 if len(items) >= 9 else (len(items) - len(items) % 3 or len(items))
        first, rest = items[:shown], items[shown:]
        more = ""
        if rest:
            more = """
          <details class="gp-more">
            <summary class="gp-more__btn">See more</summary>
            <div class="gp-presslist mt-4">
%s
            </div>
          </details>""" % "\n".join(card(*c) for c in rest)
        panels.append("""        <div class="gp-panel%s" id="panel-y%s" role="tabpanel" aria-labelledby="tab-y%s"%s>
          <div class="gp-presslist">
%s
          </div>%s
        </div>""" % (" is-on" if n == 0 else "", y, y, "" if n == 0 else " hidden",
                     "\n".join(card(*c) for c in first), more))

    body += """
  <!-- ============================================================= press -->
  <!-- DATA: all %d cards, read by clicking SEE MORE until it was gone
       (crawl/prod_interact.js, %s). Order is theirs; the year tabs come
       from each card's own date line. corporate-bonds' folder tabs and blog
       card, driven by the shared _tabs.js. Their first two cards carry each
       other's descriptions; reproduced as captured. -->
  <section class="gp-section" id="press">
    <div class="gp-shell">
      <div class="gp-tabs mb-6">
        <div class="gp-tabs__track" role="tablist" aria-label="Year">
          <span class="gp-tabs__ink" aria-hidden="true"></span>
%s
        </div>
      </div>
%s
    </div>
  </section>
""" % (len(cards), SNAPSHOT, tabs, "\n".join(panels))
    tabs_js = "<script>\n%s</script>\n" % open(os.path.join(HERE, "_tabs.js"), encoding="utf-8").read()
    page("media", "Media | GoldenPi", "Goldenpi media",
         "Media, rebuilt from goldenpi.com/media on corporate-bonds.html's components.", body, tabs_js)


if __name__ == "__main__":
    sgb()
    gsec()
    better()
    media()
