#!/usr/bin/env python3
"""Generate the four post-login landing pages from the goldenpi.com capture.

    user-explore.html          <- https://goldenpi.com/user/explore
    user-explore-no-kyc.html   <- the same, no banner configured, KYC incomplete
    user-fixed-deposits.html   <- https://goldenpi.com/user/fixed-deposits
    user-corporate-bonds.html  <- https://goldenpi.com/user/corporate-bonds
    user-bond-ipo-online.html  <- https://goldenpi.com/user/bond-ipo-online

Captured 2026-09-26, logged in (node crawl/login.js --prod, then
node crawl/snap.js --auth --prod ...). The account holder's name is replaced by
"INVESTOR" and marked data-user so developers know it is per-user.

Same stack as the four public pages: the <head>, promo bar, header, footer and
scripts are lifted from corporate-bonds.html so they cannot drift, the header
switched to its logged-in state. Sections reuse the existing gp-* components;
the few new ones live in assets/user.css.

Copy is read from content/prod_user_*.md where it repeats (FAQ, reviews,
blogs) and otherwise transcribed from it. Production renders several controls
as buttons rather than links (IPO Invest, blog cards, collection cards); those
link only where the crawl saw a URL, and stay buttons otherwise.

Run: python3 pages/_user.py
"""
import html
import os
import re

import _final as F
import _convert as C

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PROD = "https://goldenpi.com"
UAT = F.BASE

NAME = '<span data-user="first-name">INVESTOR</span>'


def md(slug):
    with open(os.path.join(ROOT, "content", "prod_user_%s.md" % slug), encoding="utf-8") as f:
        return f.read()


def rendered(slug):
    with open(os.path.join(ROOT, "crawl", "rendered", "prod_user_%s.html" % slug),
              encoding="utf-8") as f:
        return html.unescape(f.read())


def esc(s):
    return html.escape(s, quote=False)


def local_img(url):
    """Local file for a captured image URL, via assets/img-map.tsv."""
    with open(os.path.join(ROOT, "assets", "img-map.tsv"), encoding="utf-8") as f:
        for row in f:
            u, _, n = row.rstrip("\n").partition("\t")
            if u == url:
                return n
    raise SystemExit("image not in img-map.tsv: %s" % url)


# ------------------------------------------------------------ copy from md

def faqs(slug):
    """[(question, [answer paragraphs])] from the page's FAQ block."""
    text = md(slug)
    block = text[text.index("### Frequently Asked Questions"):text.index("#### Need Help?")]
    out = []
    for part in block.split("\n#### ")[1:]:
        lines = [l for l in part.splitlines() if l.strip()]
        out.append((lines[0], [l[2:] for l in lines[1:] if l.startswith("- ")]))
    return out


def reviews(slug):
    """[(name, quote)] in page order, once each (the carousel repeats them)."""
    text = md(slug)
    start = text.index("\n", text.index("### Trusted by 18 Lac+"))
    block = text[start:text.index("### Your guide to invest smartly")]
    seen, out = set(), []
    for name, quote in re.findall(r"### (.+)\n\n- (.+)", block):
        if name not in seen:
            seen.add(name)
            out.append((name, quote))
    return out


def blogs(slug):
    """[(title, date, thumbnail)]: titles and dates from the md, thumbnails
    from the capture, where they are CSS backgrounds in the same order."""
    text = md(slug)
    block = text[text.index("### Your guide to invest smartly"):].split("\n### ")[0]
    items = [l[2:] for l in block.splitlines() if l.startswith("- ")]
    pairs = list(zip(items[0::2], items[1::2]))
    thumbs = re.findall(r'blog-img-container" style="background-image: url\("([^"]+)"\)',
                        rendered(slug))
    if len(thumbs) < len(pairs):
        raise SystemExit("%s: %d blog thumbnails for %d posts" % (slug, len(thumbs), len(pairs)))
    return [(t, d, local_img(u)) for (t, d), u in zip(pairs, thumbs)]


# ---------------------------------------------------------------- shell

def shell(title, desc, current):
    """Head, promo bar and logged-in header / footer and scripts, from the
    generated corporate-bonds.html."""
    with open(os.path.join(HERE, "corporate-bonds.html"), encoding="utf-8") as f:
        src = f.read()
    top = src[:src.index('<main id="main-content">')]
    bottom = src[src.index("</main>"):]

    top = re.sub(r"<title>.*?</title>", "<title>%s</title>" % title, top, count=1, flags=re.S)
    top = re.sub(r'<meta name="description" content="[^"]*">',
                 '<meta name="description" content="%s">' % desc, top, count=1)
    top = top.replace('<link rel="stylesheet" href="../assets/final.css">',
                      '<link rel="stylesheet" href="../assets/final.css">\n'
                      '<link rel="stylesheet" href="../assets/user.css">', 1)
    top = top.replace("</title>", "</title>\n<!-- Post-login page, generated by pages/_user.py "
                      "from the goldenpi.com capture of 2026-09-26. -->", 1)

    # Logged in: home is the explore page, and the nav points at the user pages.
    top = top.replace('<a href="index.html" class="flex-none">',
                      '<a href="user-explore.html" class="flex-none">', 1)
    top = top.replace(' aria-current="page"', "")
    top = top.replace("header-nav-bonds-selected.svg", "header-nav-bonds.svg")
    top = top.replace('href="corporate-bonds.html"', 'href="user-corporate-bonds.html"')
    top = top.replace('href="fixed-deposits.html"', 'href="user-fixed-deposits.html"')
    if current == "bonds":
        top = top.replace('href="user-corporate-bonds.html">\n        <img src="../assets/img/header-nav-bonds.svg"',
                          'href="user-corporate-bonds.html" aria-current="page">\n'
                          '        <img src="../assets/img/header-nav-bonds-selected.svg"', 1)
    if current == "fd":
        top = top.replace('href="user-fixed-deposits.html">\n        <img src="../assets/img/header-nav-fd.svg"',
                          'href="user-fixed-deposits.html" aria-current="page">\n'
                          '        <img src="../assets/img/header-nav-fd-selected.svg"', 1)

    # Login becomes the bell and the account avatar, both controls, not links,
    # as on the live site.
    login = re.search(r'    <button type="button" class="gp-cta gp-cta--primary gp-cta--sm flex-none ml-auto lg:ml-0">'
                      r".*?</button>\n", top, re.S)
    if not login:
        raise SystemExit("login button not found in corporate-bonds.html")
    top = top[:login.start()] + (
        '    <div class="gp-user flex-none ml-auto lg:ml-0">\n'
        '      <button type="button" class="gp-user__bell" aria-label="Notifications">\n'
        '        <img src="../assets/img/notify-bell.svg" alt="" width="20" height="20">\n'
        '      </button>\n'
        '      <!-- DATA: the account holder\'s initials. -->\n'
        '      <button type="button" class="gp-user__avatar" aria-label="Account menu">IN</button>\n'
        '    </div>\n') + top[login.end():]
    return top + '<main id="main-content">\n', "\n" + bottom


def section(banner, inner, id_=None, cls="gp-section gp-section--tight gp-section--flush-top"):
    rule = "=" * max(4, 66 - len(banner))
    return ('  <!-- %s %s -->\n  <section data-reveal class="%s"%s>\n    <div class="gp-shell">\n'
            '%s\n    </div>\n  </section>\n' % (rule, banner, cls, ' id="%s"' % id_ if id_ else "", inner))


def head(title, extra=""):
    return ('      <div class="gp-section__head gp-section__head--marked">\n'
            '        <h2 class="gp-section__title">%s</h2>\n%s      </div>\n' % (title, extra))


# ------------------------------------------------------------ sections

def greet(title, sub, icon=None):
    img = ('      <img class="gp-greet__icon" src="../assets/img/%s" alt="" width="72" height="72">\n'
           % icon if icon else "")
    return ('  <!-- ============================================================= greeting -->\n'
            '  <!-- DATA: first name of the logged-in account. -->\n'
            '  <section class="gp-shell pt-8">\n    <div class="gp-greet">\n%s'
            '      <div>\n        <h1 class="gp-greet__title">%s</h1>\n'
            '        <p class="gp-greet__sub">%s</p>\n      </div>\n    </div>\n  </section>\n'
            % (img, title, sub))


BANNER = (
    '  <!-- =============================================================== banner -->\n'
    '  <section class="gp-shell gp-banner">\n'
    '    <img src="../assets/img/post-desk.png" width="4801" height="790" class="w-full rounded-2xl"\n'
    '         alt="No Closing Bell for Smart Investors. Yield up to 13.60% p.a., minimum investment'
    ' &#8377;30,000, credit rating up to AA. SEBI registered, OBPP licensed.">\n'
    '  </section>\n')


# One slide per product page. Copy is each page's own greeting line, and the
# CTA is its greeting's "Explore ..." phrase, so nothing here is new copy.
PRODUCTS = [
    ("Corporate Bonds", "post-login-ncd-info.svg",
     "Discover reliable income and stable capital growth with Corporate Bond Investments",
     "Explore Corporate Bonds", "user-corporate-bonds.html"),
    ("Fixed Deposits", "post-login-cfd-home.svg",
     "Invest in RBI-regulated small banks and NBFCs with Annual returns up to 8.5%",
     "Explore Fixed Deposit", "user-fixed-deposits.html"),
    ("NCD IPOs", "ipo-post-login.svg",
     "Earn more than bank FDs, with returns as high as 12%",
     "Explore NCD IPOs", "user-bond-ipo-online.html"),
]


def product_carousel():
    """CSS scroll-snap carousel. The dots are a small script on
    top; without it the slides still swipe and scroll."""
    slides = "\n".join(
        '          <li class="gp-carousel__slide" id="product-%d" aria-roledescription="slide"'
        ' aria-label="%d of %d">\n'
        '            <div class="gp-carousel__copy">\n'
        '              <h2 class="gp-carousel__title">%s</h2>\n'
        '              <p class="gp-carousel__text">%s</p>\n'
        '              <a class="gp-cta gp-cta--primary gp-cta--sm" href="%s">%s</a>\n'
        '            </div>\n'
        '            <img class="gp-carousel__art" src="../assets/img/%s" alt="" width="180" height="200">\n'
        '          </li>' % (i + 1, i + 1, len(PRODUCTS), name, text, href, cta, icon)
        for i, (name, icon, text, cta, href) in enumerate(PRODUCTS))
    dots = "\n".join('          <button type="button" class="gp-carousel__dot" aria-label="Show %s"%s></button>'
                     % (p[0], ' aria-current="true"' if i == 0 else "") for i, p in enumerate(PRODUCTS))
    return (
        '      <div class="gp-carousel" aria-roledescription="carousel" aria-label="Products">\n'
        '        <ul class="gp-carousel__track">\n%s\n        </ul>\n'
        '        <div class="gp-carousel__nav">\n'
        '%s\n'
        '        </div>\n'
        '      </div>\n'
        '      <script>\n'
        '      (function () {\n'
        '        var root = document.currentScript.previousElementSibling;\n'
        '        var track = root.querySelector(".gp-carousel__track");\n'
        '        var dots = root.querySelectorAll(".gp-carousel__dot");\n'
        '        var at = function () { return Math.round(track.scrollLeft / track.clientWidth); };\n'
        '        var go = function (i) {\n'
        '          track.scrollTo({ left: i * track.clientWidth, behavior: "smooth" });\n'
        '        };\n'
        '        dots.forEach(function (d, i) { d.addEventListener("click", function () { go(i); }); });\n'
        '        track.addEventListener("scroll", function () {\n'
        '          dots.forEach(function (d, i) {\n'
        '            if (i === at()) d.setAttribute("aria-current", "true"); else d.removeAttribute("aria-current");\n'
        '          });\n'
        '        }, { passive: true });\n'
        '      })();\n'
        '      </script>\n') % (slides, dots)


# Definitions from the portfolio page's Active investment sheet
# (_portfolio.SHEETS, Figma 4:6702), word for word.
ACTIVE_TIPS = {
    "Outstanding": "The value of all your active investments. This is the amount you will receive if holding "
                   "the investments till maturity. This excludes already sold or matured investments.",
    "Total Invested": "Total amount invested in all your active investments.",
    "Repaid": "Total amount repaid to you across all your active investments including both interest and "
              "principal repayment",
    "Gains": "Total gains from your active investments, including interest that has been repaid and accrued",
}


def tip(label):
    """The product pages' info tooltip (.gp-tip): hover or focus shows it."""
    return ('<span class="gp-tip"><button type="button" class="gp-tip__btn" aria-label="What is %s?">'
            '<img src="../assets/img/info.svg" alt="" width="14" height="14"></button>'
            '<span class="gp-tip__text" role="tooltip">%s</span></span>') % (label, ACTIVE_TIPS[label])


def active_portfolio():
    """Portfolio card, invested state: Outstanding leads, the other three
    figures sit below it. Labels and sample values follow the portfolio
    page's Active investment card."""
    rest = [("Total Invested", "100 Cr", ""), ("Repaid", "80 Cr", ""),
            ("Gains", "5 Cr", ' class="gp-active__gain"')]
    cells = "\n".join(
        '            <div>\n              <dt>%s%s</dt>\n              <dd%s>&#8377;%s</dd>\n            </div>'
        % (k, tip(k), cls, v) for k, v, cls in rest)
    return (
        '      <!-- DATA: active investment totals; sample values from the design, as on'
        ' portfolio.html. -->\n'
        '      <div class="gp-portfolio gp-portfolio--active">\n'
        '        <p class="gp-portfolio__strip">\n'
        '          <img src="../assets/img/finance_mode_gold.svg" alt="" width="18" height="18">\n'
        '          You have joined 9Lakh+ users!\n        </p>\n'
        '        <div class="gp-active">\n'
        '          <p class="gp-active__title">Active portfolio</p>\n'
        '          <p class="gp-active__lead"><span>Outstanding%s</span>'
        '<strong>&#8377;25 Cr</strong></p>\n'
        '          <dl class="gp-active__rest">\n%s\n          </dl>\n'
        '        </div>\n'
        '      </div>\n') % (tip("Outstanding"), cells)


def portfolio(card):
    return section("portfolio", '      <div class="gp-snapshot">\n' + product_carousel() + card + '      </div>')



# Shown when no promo banner is configured. Every string is captured copy:
# "500+ Bonds" / "₹3000 Cr+" from the trust stats, "View All" from the
# listing; the heading is the section's job, Explore all bonds.
FALLBACK_BANNER = (
    '  <!-- ====================================================== banner (fallback) -->\n'
    '  <!-- Rendered when the CMS returns no banner; same box as the banner image.\n'
    '       Stats are the trust-strip figures of 2026-09-26. -->\n'
    '  <section class="gp-shell gp-banner">\n'
    '    <div class="gp-fallback">\n'
    '      <div class="gp-fallback__inner">\n'
    '        <div>\n'
    '          <h2 class="gp-fallback__title">Explore all bonds</h2>\n'
    '          <ul class="gp-fallback__stats">\n'
    '            <li><strong>500+ Bonds</strong>explore from variety of bonds</li>\n'
    '            <li><strong>&#8377;3000 Cr+</strong>worth of bonds available on the platform everyday</li>\n'
    '          </ul>\n'
    '        </div>\n'
    '        <img class="gp-fallback__art" src="../assets/img/All_Bonds.svg" alt="" width="160" height="160">\n'
    '        <a class="gp-cta gp-cta--primary gp-cta--sm gp-fallback__cta" href="collections-all-bonds.html"'
    ' aria-label="Explore all bonds">\n'
    '          <span class="gp-fallback__label">View All</span>\n'
    '          <img class="gp-fallback__arrow" src="../assets/img/explore-collection-right-arrow.svg" alt=""'
    ' width="14" height="14">\n'
    '        </a>\n'
    '      </div>\n'
    '    </div>\n'
    '  </section>\n')


def portfolio_no_kyc():
    """Portfolio card for an account without KYC: no values, one message,
    and two ways forward. Heading, support line and CTA were supplied by the
    user on 2026-10-01, not captured from the live site."""
    return (
        '      <!-- Shown instead of the portfolio card until KYC is complete. -->\n'
        '      <div class="gp-portfolio gp-portfolio--nokyc">\n'
        '        <span class="gp-nokyc__icon"><img src="../assets/img/check-kyc.svg" alt=""'
        ' width="26" height="26"></span>\n'
        '        <p class="gp-nokyc__title">Complete KYC to start investing</p>\n'
        '        <p class="gp-nokyc__sub">Need help with KYC or bond investing? Our Support Team is here to help you understand how bonds work.</p>\n'
        '        <div class="gp-nokyc__ctas">\n'
        '          <button type="button" class="gp-cta gp-cta--primary">Continue KYC</button>\n'
        '          <a class="gp-cta gp-cta--secondary" href="tel:080-45685666">\n'
        '            <img src="../assets/img/phone-icon.svg" alt="" width="14" height="14">080-45685666</a>\n'
        '        </div>\n'
        '      </div>\n')


def page_explore_no_kyc():
    """Explore with no banner configured and KYC incomplete. Pending orders
    is dropped: an account without KYC cannot place one."""
    return [
        greet("Hi %s!" % NAME, "Let GoldenPi help you start your fixed-income investment journey"),
        FALLBACK_BANNER,
        portfolio(portfolio_no_kyc()),
        listing("Special Corporate Bond Deals for you!", explore_tabs()),
        recently_viewed(),
        collections(),
        quiz(),
        trusted("explore"),
        blog_section("explore"),
        faq("explore"),
    ]


# Rows exactly as the capture shows them: the new yield, the old one struck.
PROD_ROWS = [
    ("NEOGROWTH", "GPID104095.Neogrowth-new-logo-1-.jpg", "13%", "12.8%", "ICRA BBB",
     "Quarterly", "19 Months",
     "/bonds/INE814O07634/neogrowth-bond-yield?src=view_details&tenureDate=30-Apr-2028"),
    ("AKARA", "GPID102720.AKARA-CAPITAL-ADVISORS-PRIVATE-LIMITED-2x.png", "13%", "12.7%",
     "ACUITE BBB+", "Monthly", "36 Months",
     "/bonds/INE08XP07530/akara-bond-yield?src=view_details&tenureDate=18-Sep-2029"),
    ("BEST CAPITAL", "GPID107347.Best-Capital.png", "13%", "12.7%", "IVR BBB",
     "Monthly", "36 Months",
     "/bonds/INE04UP07246/best-capital-bond-yield?src=view_details&tenureDate=11-Sep-2029"),
    ("NEOGROWTH", "GPID104095.Neogrowth-new-logo-1-.jpg", "12.75%", "12.24%", "ICRA BBB",
     "Quarterly", "10 Months",
     "/bonds/INE814O07634/neogrowth-bond-yield?src=view_details&tenureDate=30-Jul-2027"),
]


def prod_rows():
    out = []
    for i, (name, logo, ret, was, rating, payout, tenure, href) in enumerate(PROD_ROWS):
        row = F.row_html((name, logo, '%s <s class="gp-was">%s</s>' % (ret, was), rating,
                          payout, tenure, href), i, "Payout", "Tenure")
        row = row.replace(UAT + "/bonds/", PROD + "/bonds/")
        out.append(row)
    return C.listing_body("\n\n".join(out), ("Returns", "Credit Rating", "Payout", "Tenure"),
                          "View All", "/bond-utsav").replace(UAT + "/bond-utsav", PROD + "/bond-utsav")


def listing(title, tabs):
    return section("listing", head(title) + C.cream(C.tabstrip(tabs)).replace(
        'aria-label="Categories"', 'aria-label="Bond categories"'))


def explore_tabs():
    """The homepage's six tabs; production's captured rows in the first."""
    tabs = C.home_tabs()
    tabs[0]["body"] = ("          <!-- DATA: Bond Utsav deals, goldenpi.com 2026-09-26. The other\n"
                       "               panels reuse the uatnew snapshot of 2026-09-25: production\n"
                       "               renders only the selected tab. -->\n" + prod_rows())
    tabs[2]["label"] = "Bonds at &#8377;30,000"
    return tabs


def corporate_tabs():
    """Production's six tabs, in its order, over corporate-bonds' data."""
    by_id = {t["id"]: t for t in F.TABS}
    tabs = []
    for tid, label in (("utsav", "Bond Utsav Deals"), ("yield", "11%+ Yield Bonds"),
                       ("thirtyk", "Bonds at &#8377;30,000"), ("monthly", "Bonds for Monthly Income"),
                       ("rated", "High Rated Bonds"), ("ipo", "NCD IPO")):
        t = by_id[tid]
        rows = "\n\n".join(F.row_html(r, i, t["col4"], t["col5"]) for i, r in enumerate(t["rows"]))
        body = C.listing_body(rows, ("Returns", "Credit Rating", t["col4"], t["col5"]),
                              t["more"][0], t["more"][1])
        tabs.append(dict(id=tid, label=label, icon=t["icon"], body=body))
    tabs[0]["body"] = explore_tabs()[0]["body"]
    return tabs


def collections():
    """The shared five-card bento, pointed at production."""
    return F.collections("Our Bond Collections").replace(UAT, PROD)


def quiz():
    opts = [("High Rated", "AAA Credit Rating"), ("High Returns", "Yield more than 11%"),
            ("One-time payout", "On Maturity"), ("Regular Income", "Monthly Payout")]
    buttons = "\n".join(
        '          <button type="button" class="gp-quiz__opt"><strong>%s</strong><span>%s</span></button>' % o
        for o in opts)
    return section("goal quiz", (
        '      <div class="gp-quiz">\n'
        '        <div class="gp-quiz__top">\n'
        '          <img src="../assets/img/tent-icon.svg" alt="" width="56" height="56">\n'
        '          <div class="min-w-0 flex-1">\n'
        '            <h2 class="gp-quiz__title">Help us set personalised goals for you</h2>\n'
        '            <p class="gp-quiz__sub">Take our short quiz!</p>\n'
        '          </div>\n'
        '          <div class="gp-quiz__progress">\n'
        '            <p><span>1/3</span><span>0%% Complete</span></p>\n'
        '            <span class="gp-quiz__bar" role="progressbar" aria-valuenow="0" aria-valuemin="0"'
        ' aria-valuemax="100" aria-label="Quiz progress"></span>\n'
        '          </div>\n'
        '        </div>\n'
        '        <p class="gp-quiz__q">What is the purpose of your investment?</p>\n'
        '        <div class="gp-quiz__opts">\n%s\n        </div>\n'
        '      </div>') % buttons)


def ipo_card():
    return (
        '      <!-- DATA: live NCD IPOs, goldenpi.com 2026-09-26. Invest is a control, not\n'
        '           a link, on the live site. -->\n'
        '      <article class="gp-card relative p-5 sm:p-6 sm:pt-12">\n'
        '        <p class="gp-ipo-flag">\n'
        '          <img src="../assets/img/star.gif" alt="" width="14" height="14">\n'
        '          <span><strong>47.06% more</strong> than Bank FDs*</span>\n'
        '        </p>\n'
        '        <div class="grid gap-5 sm:grid-cols-[minmax(0,1.3fr)_repeat(3,minmax(0,1fr))_auto] sm:items-center">\n'
        '          <div class="flex items-center gap-3">\n'
        '            <img src="../assets/img/GPID100778.EDELWEISS-FINANCIAL-SERVICES-LIMITED.png" alt=""\n'
        '                 width="44" height="44" class="flex-none rounded-lg">\n'
        '            <h3 class="t-body font-bold leading-snug">EDELWEISS FINANCIAL SERVICES LIMITED</h3>\n'
        '          </div>\n'
        '          <div><p class="gp-row__label">Credit Rating</p><p class="gp-row__value">A+/STABLE CRISIL</p></div>\n'
        '          <div><p class="gp-row__label">Returns upto</p><p class="gp-row__value gp-row__value--returns">10%</p></div>\n'
        '          <div>\n'
        '            <p class="gp-row__label">Closes on*</p>\n'
        '            <p class="gp-row__value">5-Oct-2026</p>\n'
        '            <p class="mt-1 t-caption font-semibold text-[#a05a1f]">\n'
        '              <img src="../assets/img/FastFilling.svg" alt="" width="12" height="12" class="inline"> Fast Filling</p>\n'
        '          </div>\n'
        '          <button type="button" class="gp-cta gp-cta--primary gp-cta--sm">Invest</button>\n'
        '        </div>\n'
        '      </article>')


def live_ipos():
    chips = ('        <p class="gp-chips">\n'
             '          <span><img src="../assets/img/credit-card.svg" alt="" width="14" height="14">'
             ' Start with just &#8377; 10,000</span>\n'
             '          <span><img src="../assets/img/encrypted.svg" alt="" width="14" height="14">'
             ' No KYC Required</span>\n        </p>\n')
    return section("live ipos", head("Live NCD IPOs", chips) + C.cream(ipo_card()))


def explainer(title, paras, terms, img, band=None):
    ps = "\n".join('        <p class="mt-4 t-body t-muted">%s</p>' % p for p in paras)
    chips = "\n".join('          <span class="rounded-full border border-stroke bg-white px-3 py-1.5">%s</span>'
                      % t for t in terms)
    band_html = ""
    if band:
        band_html = (
            '\n\n      <div class="gp-calc-band">\n'
            '        <img src="../assets/img/calc.svg" alt="" width="56" height="40">\n'
            '        <p>%s</p>\n'
            '        <a class="gp-cta gp-cta--secondary gp-cta--sm" href="#fd-calculator">%s</a>\n'
            '      </div>' % band)
    return section("explainer", (
        '      <div class="grid gap-8 md:grid-cols-[1.4fr_0.6fr] md:items-center">\n'
        '      <div>\n'
        '        <h2 class="gp-section__title text-left">%s</h2>\n%s\n'
        '        <div class="mt-6 flex flex-wrap items-center gap-2 t-small">\n'
        '          <span class="font-semibold">What it means?</span>\n%s\n'
        '        </div>\n'
        '      </div>\n'
        '      <img src="../assets/img/%s" alt="" width="220" height="220" class="mx-auto h-auto max-h-56 w-auto max-w-[220px]">\n'
        '      </div>%s') % (title, ps, chips, img, band_html))


def blog_section(slug):
    cards = "\n".join(
        '        <a class="gp-blogcard" href="%s/blog">\n'
        '          <span class="gp-blogcard__body">\n'
        '            <span class="gp-blogcard__title">%s</span>\n'
        '            <span class="gp-blogcard__meta">%s</span>\n'
        '            <span class="gp-blogcard__more">Read more\n'
        '              <img src="../assets/img/SVG-1.png" alt="" width="14" height="14"></span>\n'
        '          </span>\n'
        '          <img class="gp-blogcard__media gp-blogcard__media--wide" src="../assets/img/%s" alt=""'
        ' width="1600" height="900">\n'
        '        </a>' % (PROD, esc(t), esc(d), img) for t, d, img in blogs(slug))
    return section("blog", head("Your guide to invest smartly") + (
        '      <!-- DATA: blog feed, goldenpi.com 2026-09-26. The live cards open their post\n'
        '           from a click handler with no link in the markup, so these point at /blog. -->\n'
        '      <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">\n%s\n      </div>') % cards)


AVATARS = {"sumit dhar": "sumit.png", "Sivasakthi Thangavel": "sivasakthi.png", "Shyju K.J": "shyju.png",
           "Ankur Arya": "ankur.png", "Moni Ponia": "moni.png", "Atanu Moitra": "atanu.png",
           "Patrique Veda": "patrique.png", "Bhaskar Sohoni": "bhaskar.png",
           "Sitikantha Prusty": "sitikantha.png"}


def trusted(slug):
    stats = [("&#8377;3000 Cr+", "worth of bonds available on the platform everyday"),
             ("18 Lac+", "registered users &amp; growing"),
             ("&#8377;6300 Cr+", "total transaction through our platform"),
             ("500+ Bonds", "explore from variety of bonds")]
    strip = "\n".join(
        '        <div class="gp-stats__item">\n'
        '          <span class="gp-stats__value">%s</span>\n'
        '          <span class="gp-stats__label">%s</span>\n'
        '        </div>' % s for s in stats)
    revs = reviews(slug)

    def card(name, quote, hidden):
        return (
            '          <figure class="gp-review"%s>\n'
            '            <figcaption class="gp-review__head">\n'
            '              <img class="gp-review__avatar" src="../assets/img/%s" alt="" width="56" height="56">\n'
            '              <span>\n'
            '                <span class="gp-review__name">%s</span>\n'
            '                <span class="gp-review__stars" aria-label="5 out of 5 stars">&#9733;&#9733;&#9733;&#9733;&#9733;</span>\n'
            '              </span>\n'
            '            </figcaption>\n'
            '            <blockquote class="gp-review__text">%s</blockquote>\n'
            '          </figure>' % (' aria-hidden="true"' if hidden else "", AVATARS[name], esc(name), esc(quote)))

    track = "\n".join([card(n, q, False) for n, q in revs] + [card(n, q, True) for n, q in revs])
    partners = "\n".join(
        '        <img src="../assets/img/%s" alt="%s" height="40">' % p
        for p in (("centrum.png", "Centrum"), ("AxisSecurities.png", "Axis Securities"),
                  ("AnandRathi.webp", "Anand Rathi"), ("Sakthi-Finance-logo.png", "Sakthi Finance")))
    return section("trusted", head("Trusted by 18 Lac+ users and Market Leaders") + (
        '      <div class="gp-stats mb-6">\n%s\n      </div>\n\n'
        '      <!-- DATA: Google reviews, goldenpi.com 2026-09-26. -->\n'
        '      <div class="gp-reviews">\n        <div class="gp-reviews__track" style="--n:%d">\n%s\n'
        '        </div>\n      </div>\n\n'
        '      <div class="gp-partners" aria-label="Market leaders we work with">\n%s\n      </div>')
        % (strip, len(revs), track, partners))


def faq(slug):
    items = []
    for k, (q, answer) in enumerate(faqs(slug)):
        body = "".join("<p>%s</p>" % esc(a) for a in answer)
        items.append(
            '        <details class="gp-faq__item"%s>\n'
            '          <summary class="gp-faq__q">%s</summary>\n'
            '          <div class="gp-faq__a">%s</div>\n'
            '        </details>' % (" open" if k == 0 else "", esc(q), body))
    html_ = section("faq", head("Frequently Asked Questions") +
                    '      <div class="gp-faq">\n%s\n      </div>' % "\n".join(items))
    return F.faq_with_help(html_, PROD + "/contact-us")


def steps(title, items, chips=None):
    chip_html = ""
    if chips:
        chip_html = ('        <p class="gp-chips">\n%s\n        </p>\n' % "\n".join(
            '          <span><img src="../assets/img/%s" alt="" width="14" height="14"> %s</span>' % c
            for c in chips))
    lis = "\n".join(
        '        <li>\n'
        '          <img src="../assets/img/%s" alt="" width="48" height="48">\n'
        '          <p class="gp-steps__num"><span>%02d</span></p>\n'
        '          <p class="gp-steps__title">%s</p>\n'
        '        </li>' % (icon, i + 1, text) for i, (icon, text) in enumerate(items))
    return section("steps", head(title, chip_html) +
                   '      <ol class="gp-steps gp-steps--icons">\n%s\n      </ol>' % lis)


# ---------------------------------------------------------------- pages

# Both blocks are per-account and empty on the production capture, so their
# content is transcribed from reference screenshots supplied on 2026-09-26.
# Satin and PFC logos are cropped from those screenshots; the crawl never saw
# those bonds, so only NEOGROWTH links anywhere.
PENDING = [("NEOGROWTH", "GPID104095.Neogrowth-new-logo-1-.jpg", "13.00%", "&#8377; 1,01,874.54")]
RECENT = [
    ("NEOGROWTH", "GPID104095.Neogrowth-new-logo-1-.jpg", "13.00%", PROD_ROWS[0][7]),
    ("SATIN FINSERV", "satin-finserv-logo.png", "11.90%", None),
    ("POWER FINANCE", "pfc-logo.png", "6.85%", None),
]

HOURGLASS = ('<svg viewBox="0 0 24 32" width="28" height="36" aria-hidden="true" fill="none" '
             'stroke="#322811" stroke-width="1.6" stroke-linejoin="round">'
             '<rect x="3" y="1" width="18" height="3" rx="1.5"/><rect x="3" y="28" width="18" height="3" rx="1.5"/>'
             '<path d="M5 4c0 7 7 8 7 12s-7 5-7 12h14c0-7-7-8-7-12s7-5 7-12"/>'
             '<path d="M7.5 27c1-3 3-4 4.5-4.5 1.5.5 3.5 1.5 4.5 4.5z" fill="#d4af37" stroke="none"/></svg>')


def pending_orders():
    cards = "\n".join(
        '          <article class="gp-pending__card">\n'
        '            <p class="gp-pending__gain">+%s returns if invested\n'
        '              <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor"'
        ' stroke-width="1.8" stroke-linecap="round" aria-hidden="true"><path d="M3 13l5-5 4 3 7-7M15 4h4v4'
        'M4 21v-2M8 21v-5M12 21v-4M16 21v-7M20 21v-9"/></svg></p>\n'
        '            <div class="gp-pending__body">\n'
        '              <div class="gp-pending__id">\n'
        '                <img src="../assets/img/%s" alt="%s" width="84" height="42">\n'
        '                <div>\n                  <h3>%s</h3>\n'
        '                  <p><b>%s</b> Yield <span aria-hidden="true">|</span> <span class="whitespace-nowrap">%s</span></p>\n'
        '                </div>\n              </div>\n'
        '              <div class="gp-pending__actions">\n'
        '                <button type="button" class="gp-cta gp-cta--primary gp-cta--sm">Try Again</button>\n'
        '                <span class="gp-pending__alert" role="img" aria-label="Payment failed">!</span>\n'
        '                <button type="button" class="gp-pending__delete" aria-label="Delete %s order">\n'
        '                  <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor"'
        ' stroke-width="1.6" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13M10 11v6M14 11v6"/></svg>\n'
        '                </button>\n'
        '              </div>\n            </div>\n          </article>'
        % (ret, logo, name, name, ret, amt, name) for name, logo, ret, amt in PENDING)
    return section("pending orders", (
        '      <!-- DATA: the account\'s unpaid orders; collapsed until opened. -->\n'
        '      <details class="gp-pending">\n'
        '        <summary>\n'
        '          <span class="gp-pending__icon">%s<span class="gp-pending__count">%d</span></span>\n'
        '          <h2 class="gp-pending__title">Pending Orders</h2>\n'
        '          <span class="gp-pending__chip">Corporate Bonds</span>\n'
        '          <img class="gp-pending__caret" src="../assets/img/pending-order-arrow-down.svg" alt="" width="14" height="8">\n'
        '        </summary>\n'
        '        <div class="gp-pending__list">\n%s\n        </div>\n'
        '      </details>') % (HOURGLASS, len(PENDING), cards))


def recently_viewed():
    def card(name, logo, ret, href):
        tag, attr = ("a", ' href="%s%s"' % (PROD, href)) if href else ("div", "")
        return ('          <%s class="gp-card gp-recent__card%s"%s>\n'
                '            <p class="gp-recent__return">Potential Return <b>%s</b></p>\n'
                '            <div class="gp-recent__id">\n'
                '              <img src="../assets/img/%s" alt="%s" width="120" height="60">\n'
                '              <h3>%s<span>Corporate Bond</span></h3>\n'
                '            </div>\n          </%s>'
                % (tag, " gp-card--link" if href else "", attr, ret, logo, name, name, tag))
    cards = "\n".join(card(*r) for r in RECENT)
    return section("recently viewed", head("Recently Viewed") +
                   '      <!-- DATA: bonds this account opened most recently. -->\n'
                   '      <div class="gp-recent">\n%s\n      </div>' % cards)


def page_explore():
    return [
        greet("Hi %s!" % NAME, "Let GoldenPi help you start your fixed-income investment journey"),
        BANNER,
        portfolio(active_portfolio()),
        pending_orders(),
        listing("Special Corporate Bond Deals for you!", explore_tabs()),
        recently_viewed(),
        collections(),
        quiz(),
        trusted("explore"),
        blog_section("explore"),
        faq("explore"),
    ]


FD_ROWS = [
    ("UNITY SMALL FINANCE BANK", "GPID105192.Unity.png", "8.5%", "Insured upto &#8377;5L"),
    ("SURYODAY SMALL FINANCE BANK", "GPID105191.Suryoday.png", "8.5%", "Insured upto &#8377;5L"),
    ("UTKARSH SMALL FINANCE BANK", "GPID106947.utkarsh_logo.png", "8.25%", "CRISIL AAA"),
]


def fd_options():
    rows = "\n\n".join(
        '            <article class="gp-row" style="--r:%d">\n'
        '              <div class="gp-row__identity">\n'
        '                <img class="gp-row__logo" src="../assets/img/%s" alt="">\n'
        '                <span class="gp-row__name">%s</span>\n'
        '              </div>\n'
        '              <div><div class="gp-row__label">Highest Returns</div>'
        '<div class="gp-row__value gp-row__value--returns">%s</div></div>\n'
        '              <div><div class="gp-row__label">Secured</div><div class="gp-row__value">%s</div></div>\n'
        '              <div><div class="gp-row__label">Tenure</div><div class="gp-row__value">7 D - 60 M</div></div>\n'
        '              <div></div>\n'
        '              <div class="gp-row__actions"></div>\n'
        '            </article>' % (i, logo, name, ret, sec) for i, (name, logo, ret, sec) in enumerate(FD_ROWS))
    feats = ('          <ul class="gp-checks">\n'
             '            <li><img src="../assets/img/check_circle.svg" alt="" width="18" height="18">'
             ' DICGC insurance up to &#8377;5 lakh</li>\n'
             '            <li><img src="../assets/img/check_circle.svg" alt="" width="18" height="18">'
             ' Monthly and quarterly payouts available</li>\n'
             '          </ul>\n')
    bank = (feats + '          <!-- DATA: bank FDs, goldenpi.com 2026-09-26. -->\n'
            '          <div class="gp-rows__head">\n'
            '            <span></span><span>Highest Returns</span><span>Secured</span>\n'
            '            <span>Tenure</span><span></span><span></span>\n'
            '          </div>\n\n'
            '          <div class="gp-rows">\n%s\n          </div>' % rows)

    def empty(kind):
        return ('          <div class="gp-card p-10 text-center">\n'
                '            <p class="t-body t-muted m-0">%s were not captured: the live page\n'
                '              renders only the selected tab.</p>\n'
                '            <p class="mt-4 m-0"><a class="t-small font-bold t-bronze underline"\n'
                '               href="%s/fixed-deposits">See the live fixed deposit list</a></p>\n'
                '          </div>' % (kind, PROD))

    tabs = [dict(id="bank", label="Bank FD", icon="bank-fd.svg", body=bank),
            dict(id="tax", label="Tax Saving FD", icon="tax-saving-fd.svg", body=empty("Tax saving FDs")),
            dict(id="nbfc", label="NBFC FD", icon="nbfc-fd.svg", body=empty("NBFC FDs"))]
    extra = '        <p class="gp-section__sub">Highest returns up to 8.5% pa</p>\n'
    return section("fd options", head("Available Fixed Deposit Options", extra) + C.cream(C.tabstrip(tabs)))


def fd_calculator():
    chips = "\n".join('          <span class="gp-pill">%s</span>' % c
                      for c in ("Senior citizen", "Female", "Tax Saver", "Bank FD", "NBFC"))
    plans = "\n".join(
        '          <article class="gp-card flex items-center gap-4 p-4">\n'
        '            <img src="../assets/img/%s" alt="" width="40" height="40" class="flex-none">\n'
        '            <div class="min-w-0 flex-1">\n'
        '              <p class="t-body font-bold">%s</p>\n'
        '              <dl class="mt-2 grid grid-cols-3 gap-2 t-small">\n'
        '                <div><dt class="t-caption t-muted">Returns</dt><dd class="font-bold text-gain">%s</dd></div>\n'
        '                <div><dt class="t-caption t-muted">Tenure</dt><dd class="font-bold">60 Months</dd></div>\n'
        '                <div><dt class="t-caption t-muted">Payout</dt><dd class="font-bold">Cumulative</dd></div>\n'
        '              </dl>\n'
        '            </div>\n'
        '            <button type="button" class="gp-cta gp-cta--primary gp-cta--sm flex-none">Invest</button>\n'
        '          </article>' % p for p in (("GPID105191.Suryoday.png", "Suryoday Small Finance Bank", "8.25%"),
                                              ("GPID100016.Shriram-Squircle.png", "Shriram Finance", "7.5%")))
    return section("calculator", head("Let's find the best FD offerings for your needs!") + (
        '      <!-- DATA: the calculator as captured with its defaults. Wire it to the same\n'
        '           calculator as fixed-deposits.html (#fd-calculator); production compounds\n'
        '           quarterly, which is how 8.25%% over 60 months gives the figures below. -->\n'
        '      <div class="gp-card p-5 sm:p-8">\n'
        '        <div class="mb-6 flex flex-wrap gap-2">\n%s\n        </div>\n'
        '        <div class="grid gap-8 lg:grid-cols-2">\n'
        '          <dl class="gp-calc-inputs">\n'
        '            <div><dt>Investment Amount</dt><dd>&#8377; 2,00,000</dd></div>\n'
        '            <div><dt>Tenure (Months)</dt><dd>60</dd></div>\n'
        '            <div><dt>Payout Mode</dt><dd>On maturity</dd></div>\n'
        '            <div><dt>Interest Rate</dt><dd class="text-gain">8.25%%</dd></div>\n'
        '          </dl>\n'
        '          <dl class="gp-calc-result">\n'
        '            <div><dt>Invested Amount</dt><dd>&#8377; 2,00,000</dd></div>\n'
        '            <div><dt>FD Gains</dt><dd>&#8377; 1,00,852.79</dd></div>\n'
        '            <div><dt>Maturity Amount</dt><dd>&#8377; 3,00,852.79</dd></div>\n'
        '          </dl>\n'
        '        </div>\n'
        '        <p class="mt-8 mb-3 t-body font-bold t-bronze">Here are the best FD plans for you!</p>\n'
        '        <div class="grid gap-4 md:grid-cols-2">\n%s\n        </div>\n'
        '      </div>') % (chips, plans), id_="fd-calculator")


def page_fd():
    return [
        greet("Hi %s, Explore Fixed Deposit" % NAME,
              "Invest in RBI-regulated small banks and NBFCs with Annual returns up to 8.5%",
              "cfd-post-login-home.svg"),
        BANNER,
        fd_options(),
        collections(),
        fd_calculator(),
        steps("How to invest in a FD?", [("ipo-2.png", "Choose the desired FD"),
                                          ("ipo-1.png", "Share Required Details"),
                                          ("ipo-3.png", "Make payment to Invest")]),
        explainer("What is a Fixed Deposit Investment?",
                  ["FDs (Fixed Deposits) are investment options from banks, NBFCs, and corporates in "
                   "India. You can choose to receive a lump sum money at maturity or get regular "
                   "interest payouts (monthly, quarterly, or yearly). Senior citizens often get better "
                   "rates. Through GoldenPi you can now invest in these FDs through a seamless online "
                   "journey without opening a new bank account."],
                  ["FD", "NBFC", "Payout", "Cumulative Payout"], "post-login-cfd-home.svg",
                  band=("Calculate Your FD Returns Here", "Calculate Now")),
        blog_section("fixed-deposits"),
        trusted("fixed-deposits"),
        faq("fixed-deposits"),
    ]


DISCOVER = [
    ("NEOGROWTH", "GPID104095.Neogrowth-new-logo-1-.jpg", "&#8377; 1,01,874.54", "13%", "Quarterly", "19 Months", "ICRA BBB"),
    ("AKARA", "GPID102720.AKARA-CAPITAL-ADVISORS-PRIVATE-LIMITED-2x.png", "&#8377; 29,945.21", "13%", "Monthly", "36 Months", "ACUITE BBB+"),
    ("BEST CAPITAL", "GPID107347.Best-Capital.png", "&#8377; 29,856.92", "13%", "Monthly", "36 Months", "IVR BBB"),
    ("NEOGROWTH", "GPID104095.Neogrowth-new-logo-1-.jpg", "&#8377; 1,02,112.24", "12.75%", "Quarterly", "10 Months", "ICRA BBB"),
]

FILTERS = [
    ("Yield", ["Upto 8%", "8 - 11%", "11% +"]),
    ("Credit Rating", ["AAA (Low Risk)", "AA (Balanced)", "A &amp; Below (High Yield)"]),
    ("Payout", ["Annual", "Monthly", "Quarterly", "Half Yearly", "Thrice Yearly", "Payment on maturity"]),
    ("Minimum Investment", ["Less than 50k", "50k to 2 Lac", "2 lac to 5 lac", "5lac to 10 lac",
                            "10-50 Lac", "Above 50 lacs"]),
]


def discover():
    selects = "\n".join(
        '          <label class="gp-filter"><span class="sr-only">%s</span>\n'
        '            <select>\n              <option>%s</option>\n%s\n            </select>\n'
        '          </label>' % (name, name, "\n".join("              <option>%s</option>" % o for o in opts))
        for name, opts in FILTERS)
    cards = "\n".join(
        '          <article class="gp-card gp-discover">\n'
        '            <div class="gp-discover__id">\n'
        '              <img src="../assets/img/%s" alt="" width="100" height="50">\n'
        '              <h3>%s</h3>\n'
        '              <span class="gp-order-badge">24x7 Order</span>\n'
        '            </div>\n'
        '            <dl>\n'
        '              <div><dt>Min. Investment</dt><dd>%s</dd></div>\n'
        '              <div><dt>Yield</dt><dd class="gp-row__value--returns">%s</dd></div>\n'
        '              <div><dt>Payout</dt><dd>%s</dd></div>\n'
        '              <div><dt>Tenure</dt><dd>%s</dd></div>\n'
        '              <div><dt>Credit Rating</dt><dd>%s</dd></div>\n'
        '            </dl>\n'
        '          </article>' % ((d[1], d[0]) + d[2:]) for d in DISCOVER)
    extra = ('        <p class="gp-section__sub"><a class="t-bronze font-bold underline" '
             'href="%s/collections">View All</a></p>\n' % PROD)
    return section("discover", head("Discover Bonds with Customised Filter Options", extra) + (
        '      <!-- DATA: filters and results, goldenpi.com 2026-09-26 (no filter applied). -->\n'
        '      <div class="rounded-2xl border border-[#f0e6c8] bg-[#fdf8e9] p-4 sm:p-6">\n'
        '        <div class="mb-5 flex flex-wrap gap-3">\n%s\n        </div>\n'
        '        <div class="space-y-3">\n%s\n        </div>\n'
        '      </div>') % (selects, cards))


def page_corporate():
    return [
        greet("Hi %s, Explore Corporate Bonds" % NAME,
              "Discover reliable income and stable capital growth with Corporate Bond Investments",
              "post-login-ncd.svg"),
        BANNER,
        listing("Special Corporate Bond Deals for you!", corporate_tabs()),
        discover(),
        quiz(),
        collections(),
        live_ipos(),
        explainer("What is a Corporate Bond?",
                  ["Corporate Bonds are debt securities regulated by SEBI and issued by corporations "
                   "to raise capital from investors.",
                   "These bonds offer higher yields compared to other fixed income securities, "
                   "offering relatively attractive returns to investors."],
                  ["Debt Security", "Yield", "Fixed Income Security"], "post-login-ncd-info.svg"),
        blog_section("corporate-bonds"),
        trusted("corporate-bonds"),
        faq("corporate-bonds"),
    ]


CLOSED = [
    ("MUTHOOT FINCORP LIMITED", "GPID100936.MUTHOOT-FINCORP-LIMITED_1-2x.png", "AA CRISIL", "9.25%", "22-Sep-2026", "-"),
    ("Kosamattam Finance Limited", "GPID100133.Kosamattam-Finance-Limited.png", "A IND", "10%", "01-Sep-2026", "3-Sep-2026"),
    ("INDEL MONEY LIMITED", "GPID102671.INDEL-MONEY-LIMITED-2x.png", "A- IND", "11.5%", "20-Aug-2026", "24-Aug-2026"),
    ("PAISALO DIGITAL LIMITED", "GPID103761.Screenshot-2024-08-08-171759_11zon.jpg", "AA IVR", "10.47%", "17-Aug-2026", "19-Aug-2026"),
    ("MUTHOOT FINCORP LIMITED", "GPID100936.MUTHOOT-FINCORP-LIMITED_1-2x.png", "AA CRISIL", "9.25%", "03-Jul-2026", "7-Jul-2026"),
    ("EDELWEISS FINANCIAL SERVICES L...", "GPID100778.EDELWEISS-FINANCIAL-SERVICES-LIMITED.png", "A+ CRISIL", "10%", "12-Jun-2026", "16-Jun-2026"),
]


def closed_ipos():
    rows = "\n".join(
        '            <tr>\n'
        '              <td><span class="gp-table__name"><img src="../assets/img/%s" alt="" width="50" height="32">%s</span></td>\n'
        '              <td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>-</td>\n'
        '            </tr>' % ((c[1], c[0]) + c[2:]) for c in CLOSED)
    return section("closed ipos", head("Closed Bond/NCD IPOs") + (
        '      <!-- DATA: closed IPOs, page 1 of 4, goldenpi.com 2026-09-26. -->\n'
        '      <div class="gp-table-wrap">\n'
        '        <table class="gp-table">\n'
        '          <thead>\n'
        '            <tr><th scope="col">Name</th><th scope="col">Credit Rating</th>'
        '<th scope="col">Returns upto</th><th scope="col">Closed On</th>'
        '<th scope="col">Allotment Date</th><th scope="col">More Info</th></tr>\n'
        '          </thead>\n'
        '          <tbody>\n%s\n          </tbody>\n'
        '        </table>\n'
        '      </div>\n'
        '      <p class="mt-4 text-right t-small t-muted">Page 1 / 4</p>') % rows)


def page_ipo():
    return [
        greet("Hi %s, Explore NCD IPOs" % NAME,
              "Earn more than bank FDs, with returns as high as 12%", "ipo-rocket-2x.png"),
        BANNER,
        live_ipos(),
        closed_ipos(),
        collections(),
        steps("How to apply for an IPO?",
              [("ipo-1.png", "Select IPO series"), ("ipo-2.png", "Enter the Demat &amp; UPI details"),
               ("ipo-3.png", "Accept UPI mandate for the IPO"), ("ipo-4.png", "Get bond units in your Demat")],
              chips=[("encrypted.svg", "No KYC Required"), ("clock-copy.svg", "Apply in 5 mins")]),
        explainer("What is NCD/Bond Initial Public Offering (IPO)?",
                  ["A Non-Convertible Debenture (NCD) Initial Public Offering (IPO) is a type of debt "
                   "security that companies or other entities can issue to raise funds from the public.",
                   "Investors who buy Bond IPOs in India, get an opportunity to earn regular returns "
                   "till maturity, calculated based on the predetermined coupon rate."],
                  ["NCD", "IPO", "Coupon"], "ipo-post-login.svg"),
        blog_section("bond-ipo-online"),
        trusted("bond-ipo-online"),
        faq("bond-ipo-online"),
    ]


PAGES = [
    ("user-explore.html", "explore", None, page_explore),
    ("user-explore-no-kyc.html", "explore", None, page_explore_no_kyc),
    ("user-fixed-deposits.html", "fixed-deposits", "fd", page_fd),
    ("user-corporate-bonds.html", "corporate-bonds", "bonds", page_corporate),
    ("user-bond-ipo-online.html", "bond-ipo-online", None, page_ipo),
]


def main():
    for out, slug, current, build in PAGES:
        text = md(slug)
        title = re.search(r"\*\*Title:\*\* (.+)", text).group(1)
        desc = re.search(r"\*\*Meta description:\*\* (.+)", text).group(1)
        top, bottom = shell(esc(title), html.escape(desc), current)
        body = "\n".join(build())
        page = F.primary_ctas(top + "\n" + body + bottom)
        if out == "user-explore.html":
            page = dark_footer(page)
            write_footer_page(page)
        with open(os.path.join(HERE, out), "w", encoding="utf-8") as f:
            f.write(page)
        print("%-28s %6d bytes" % (out, len(page)))


def dark_footer(page):
    """user-explore only: the index.html footer (same build, F.new_footer then
    C.fold_footer), without its Read More fold and what the fold holds and
    without the New to GoldenPi column, in a
    dark theme (F.dark_footer)."""
    page = C.fold_footer(F.new_footer(page))
    i = page.index('  <details class="ft-fold">')
    j = page.index("\n  </details>\n</footer>", i) + len("\n  </details>\n")
    copy = re.search(r'<span class="ft-copy">(.*?)</span>', page[i:j]).group(1)
    page = page[:i] + ('  <div class="gp-shell ft__inner">\n'
                       '    <p class="ft-copy ft-copy--bar">%s</p>\n'
                       '  </div>\n' % copy) + page[j:]
    # Three link columns here: New to GoldenPi is dropped.
    new = re.search(r'\n\n      <nav class="ft-col" aria-labelledby="ft-new".*?</nav>', page, re.S)
    page = page[:new.start()] + page[new.end():]
    return F.dark_footer(page, " ft--cols3")


LOVED_REVIEWS = ("sumit dhar", "Shyju K.J", "Ankur Arya")  # the three shortest, quoted whole


def loved_band():
    """footer-login3.html: "Loved by 20 Lac+ Indians" over three real reviews
    from the goldenpi.com logged-in home (content/prod_user_explore.md),
    quoted whole. The reviewers' initials are the avatars; the lit one is
    the voice on screen, and choosing one shows theirs."""
    quotes = dict(reviews("explore"))
    faces, figs = [], []
    for n, name in enumerate(LOVED_REVIEWS):
        initials = "".join(w[0] for w in re.split(r"[\s.]+", name) if w)[:2].upper()
        on = n == 0
        faces.append('        <button type="button" class="ft-love__face" aria-pressed="%s" aria-controls="ft-q%d" '
                     'aria-label="Review by %s">%s</button>\n' % ("true" if on else "false", n, esc(name), initials))
        figs.append('        <figure class="ft-love__q%s" id="ft-q%d"%s>\n'
                    '          <blockquote>&ldquo;%s&rdquo;</blockquote>\n'
                    '          <figcaption>%s</figcaption>\n        </figure>\n'
                    % (" is-on" if on else "", n, "" if on else ' aria-hidden="true"', esc(quotes[name]), esc(name)))
    return ('    <!-- COPY: "20 Lac+" is from the brief. goldenpi.com says "18 Lac+ registered users"\n'
            '         (content/prod_user_explore.md). Confirm the figure before this ships. -->\n'
            '    <!-- DATA: reviews, from the goldenpi.com reviews block. -->\n'
            '    <section class="ft-love" aria-labelledby="ft-love-title" data-reveal>\n'
            '      <h2 class="ft-love__title" id="ft-love-title">Loved by <span class="ft-love__n" data-count>20<span> Lac+</span></span> Indians</h2>\n'
            '      <div class="ft-love__voices">\n'
            '      <div class="ft-love__faces" role="group" aria-label="Reviews">\n%s      </div>\n'
            '      <div class="ft-love__quotes">\n%s      </div>\n'
            '      </div>\n'
            '    </section>\n') % ("".join(faces), "".join(figs))


def proof_band():
    """footer-login5.html: "Loved by 20 Lac+ Indians" with the credentials
    from the homepage hero (content/home.md) and the platform figures from the
    logged-in home (content/prod_user_explore.md), verbatim. The user count in
    that block is left out: it says 18 Lac+, the headline says 20 Lac+."""
    with open(os.path.join(ROOT, "content", "home.md"), encoding="utf-8") as f:
        home = f.read()
    chips = [c for c in ("SEBI registered Debt Broker", "OBPP license holder") if "- %s\n" % c in home]
    text = md("explore")
    block = text[text.index("### Trusted by 18 Lac+"):]
    block = block[:block.index("\n### ", 4)]
    items = re.findall(r"^- (.+)$", block, re.M)
    stats = [(v, l) for v, l in zip(items[::2], items[1::2]) if "Lac" not in v]
    chip_html = "".join('          <li>%s<span>%s</span></li>\n' % (
        '<img src="../assets/img/sebi-logo.svg" alt="" width="44" height="20">' if n == 0 else "", esc(c))
        for n, c in enumerate(chips))
    stat_html = "".join(
        '          <div style="--i: %d"><dt>%s</dt><dd>%s</dd></div>\n' % (n, esc(l), esc(v).replace("\u20b9", "&#8377;"))
        for n, (v, l) in enumerate(stats))
    return ('    <!-- COPY: "20 Lac+" is from the brief. goldenpi.com says "18 Lac+ registered users"\n'
            '         (content/prod_user_explore.md). Confirm the figure before this ships. -->\n'
            '    <!-- DATA: platform figures, from the goldenpi.com logged-in home. -->\n'
            '    <section class="ft-love ft-love--side ft-proof" aria-labelledby="ft-love-title" data-reveal>\n'
            '      <h2 class="ft-love__title" id="ft-love-title">Loved by <span class="ft-love__n" data-count>20<span> Lac+</span></span> Indians</h2>\n'
            '      <ul class="ft-proof__chips">\n%s      </ul>\n'
            '      <dl class="ft-proof__stats">\n%s      </dl>\n'
            '    </section>\n') % (chip_html, stat_html)


HEART_JS = r"""<script>
// footer-login6: the heart beats once, as the 20 Lac+ count-up lands (it runs
// for 1s from the moment the band is 60% in view). Nothing under reduced motion.
(function () {
  var heart = document.querySelector('.ft-proof__heart');
  if (!heart || !('IntersectionObserver' in window)) return;
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  var io = new IntersectionObserver(function (es) {
    if (!es[0].isIntersecting) return;
    io.disconnect();
    setTimeout(function () { heart.classList.add('is-beat'); }, 950);
  }, { threshold: 0.6 });
  io.observe(document.querySelector('.ft-love__n'));
})();
</script>
"""


LOVED_JS = r"""<script>
// footer-login3: the reviews crossfade every 6s while the band is on screen,
// pause on hover or focus, and stop under reduced motion. The initials pick
// a review directly. Without script the first review shows.
(function () {
  var band = document.querySelector('.ft-love');
  if (!band) return;
  var faces = band.querySelectorAll('.ft-love__face');
  var figs = band.querySelectorAll('.ft-love__q');
  var at = 0, timer = null, held = false, seen = false;
  var reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  function show(n) {
    at = n;
    figs.forEach(function (f, i) { f.classList.toggle('is-on', i === n); f.setAttribute('aria-hidden', i === n ? 'false' : 'true'); });
    faces.forEach(function (b, i) { b.setAttribute('aria-pressed', i === n ? 'true' : 'false'); });
  }
  function run() {
    clearInterval(timer);
    if (reduce || held || !seen) return;
    timer = setInterval(function () { show((at + 1) % figs.length); }, 6000);
  }
  faces.forEach(function (b, i) { b.addEventListener('click', function () { show(i); run(); }); });
  band.addEventListener('pointerenter', function () { held = true; run(); });
  band.addEventListener('pointerleave', function () { held = false; run(); });
  band.addEventListener('focusin', function () { held = true; run(); });
  band.addEventListener('focusout', function (e) { if (!band.contains(e.relatedTarget)) { held = false; run(); } });
  if ('IntersectionObserver' in window) {
    new IntersectionObserver(function (es) { seen = es[0].isIntersecting; run(); }, { threshold: 0.3 }).observe(band);
  }
})();
</script>
"""


def write_footer_page(page):
    """footer-login.html: user-explore's footer on a page of its own, like
    footer-landing.html. Head, footer and trailing scripts are user-explore's,
    so the two cannot drift."""
    head = page[:page.index("<body>")]
    head = re.sub(r"<title>.*?</title>", "<title>Footer, logged in | GoldenPi</title>", head, count=1, flags=re.S)
    head = re.sub(r'<meta name="description" content="[^"]*">',
                  '<meta name="description" content="GoldenPi site footer for logged-in pages: navigation, '
                  'registration details and compliance contacts.">', head, count=1)
    head = head.replace("<!-- Post-login page, generated by pages/_user.py",
                        "<!-- The user-explore.html footer on its own, generated by pages/_user.py", 1)
    head = re.sub(r"<!-- FINAL\. This is corporate-bonds\.html.*?-->\n", "", head, count=1, flags=re.S)
    i = page.index('<footer class="ft')
    body = ('<body>\n\n<a class="gp-skip" href="#footer">Skip to footer</a>\n\n'
            '<main>\n  <h1 class="sr-only">GoldenPi footer, logged in</h1>\n</main>\n\n'
            '<!-- ============================================================== footer -->\n')
    # footer-login.html softens the text (ft--soft); footer-login2.html keeps
    # user-explore's colours as they are.
    soft = page[i:].replace('<footer class="ft ft--dark', '<footer class="ft ft--dark ft--soft', 1)
    loved = soft.replace('  <div class="gp-shell ft__inner">\n', '  <div class="gp-shell ft__inner">\n' + loved_band(), 1)
    loved = loved.replace("</body>", LOVED_JS + "</body>", 1)
    # footer-ggn-login.html: only the company block and the loved-by band, then
    # the copyright bar.
    brand = re.search(r'      <div class="ft-brand" data-reveal>.*?\n      </div>\n', soft, re.S).group(0)
    bar = soft[soft.rindex('  <div class="gp-shell ft__inner">\n    <p class="ft-copy ft-copy--bar">'):]
    side = loved_band().replace('<section class="ft-love"', '<section class="ft-love ft-love--side"', 1)
    l4 = ('<footer class="ft ft--dark ft--soft" id="footer">\n'
          '  <div class="gp-shell ft__inner">\n    <div class="ft-l4">\n' + brand + side +
          '    </div>\n  </div>\n\n' + bar)
    l4 = l4.replace("</body>", LOVED_JS + "</body>", 1)
    # footer-login5.html: footer-ggn-login with the reviews swapped for proof
    # the capture holds: the SEBI / OBPP credentials and the platform figures.
    l5 = l4.replace(side, proof_band(), 1).replace(LOVED_JS, "", 1)
    # footer-login6.html: footer-login5 with icons, one family (Phosphor): a
    # heart beside the headline and a seal on OBPP; the figures stay plain.
    l6 = l5.replace('<section class="ft-love ft-love--side ft-proof"', '<section class="ft-love ft-love--side ft-proof ft-proof--icons"', 1)
    l6 = l6.replace('      <h2 class="ft-love__title" id="ft-love-title">',
                    '      <div class="ft-proof__head">\n'
                    '        <span class="ft-proof__heart" aria-hidden="true"><i class="ph-fill ph-heart"></i></span>\n'
                    '        <h2 class="ft-love__title" id="ft-love-title">', 1)
    l6 = l6.replace(' Indians</h2>\n', ' Indians</h2>\n      </div>\n', 1)
    l6 = l6.replace('<li><span>OBPP license holder</span></li>',
                    '<li><i class="ph ph-seal-check" aria-hidden="true"></i><span>OBPP license holder</span></li>', 1)
    l6 = l6.replace("</body>", HEART_JS + "</body>", 1)
    # footer-ggn-guest.html: footer-login on black with white type (ft--black).
    black = soft.replace('<footer class="ft ft--dark ft--soft', '<footer class="ft ft--dark ft--black', 1)
    for out, foot in (("footer-login.html", soft), ("footer-login2.html", page[i:]), ("footer-ggn-guest.html", black),
                      ("footer-login3.html", loved),
                      # footer-ggn-login.html: l4 in footer-ggn-guest's black scheme;
                      # footer-login5/6 keep the soft one they are built from.
                      ("footer-ggn-login.html", l4.replace('class="ft ft--dark ft--soft"', 'class="ft ft--dark ft--black"', 1)),
                      ("footer-login5.html", l5), ("footer-login6.html", l6)):
        with open(os.path.join(HERE, out), "w", encoding="utf-8") as f:
            f.write(head.replace("Footer, logged in |", "Footer, logged in, original colours |", 1)
                    if out == "footer-login2.html" else
                    head.replace("Footer, logged in |", "Footer, logged in, loved by |", 1)
                    if out == "footer-login3.html" else
                    head.replace("Footer, logged in |", "Footer, logged in, minimal |", 1)
                    if out == "footer-ggn-login.html" else
                    head.replace("Footer, logged in |", "Footer, logged in, credentials |", 1)
                    if out == "footer-login5.html" else
                    head.replace("Footer, logged in |", "Footer, logged in, black |", 1)
                    if out == "footer-ggn-guest.html" else
                    head.replace("Footer, logged in |", "Footer, logged in, with icons |", 1).replace(
                        "</head>", '<link rel="stylesheet" href="https://unpkg.com/@phosphor-icons/web@2.1.1/src/regular/style.css">\n'
                        '<link rel="stylesheet" href="https://unpkg.com/@phosphor-icons/web@2.1.1/src/fill/style.css">\n</head>', 1)
                    if out == "footer-login6.html" else head)
            f.write(body + foot)
        print("%-28s" % out)


if __name__ == "__main__":
    main()
