#!/usr/bin/env python3
"""Vendor the production CSS a generated page needs and the local stylesheets lack.

The FD blocks on pages/fd-details.html are production's markup. This script
lists every class on the page, drops the ones the page's local stylesheets
(and inline <style>) already define (except a job's component families,
always taken whole), and copies from production's bundles
only the rules whose selectors name a missing class, with their @media /
@supports wrappers. CSS variables those rules use and nothing local defines
are copied as one :root block.

    python3 crawl/vendor_css.py fd     # pages/fd-details.html -> assets/beta/fd.css
"""
import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JOBS = {
    "fd": ("pages/fd-details.html", "assets/beta/fd.css",
           "crawl/rendered/beta_fixed-deposits_GPID105192_unity-small-finance-bank/rendered.html",
           # Production components whose rules are always taken whole: their base classes also exist locally
           # (assets/beta/ipo.css, bond-details7's beta CSS) in other variants, so "missing" alone misses them.
           ("ipo-series", "ipo-surface-card", "fd-", "issuer-need-help", "gp-expand--faq")),
}
BETA = "https://beta.goldenpi.com"


def esc(token):
    """A class name as it appears in a CSS selector (Tailwind escaping)."""
    return "".join(c if c.isalnum() or c in "-_" else "\\" + c for c in token)


def rules(css):
    """Top-level (selector, body) pairs; nested at-rule bodies are left raw."""
    out, i = [], 0
    while True:
        j = css.find("{", i)
        if j < 0:
            return out
        depth, k = 1, j + 1
        while depth:
            depth += (css[k] == "{") - (css[k] == "}")
            k += 1
        out.append((css[i:j].strip(), css[j + 1:k - 1]))
        i = k


def pick(css, wanted):
    keep = []
    for sel, body in rules(css):
        if sel.startswith(("@media", "@supports", "@layer", "@container")):
            inner = pick(body, wanted)
            if inner:
                keep.append("%s{%s}" % (sel, inner))
        elif not sel.startswith("@") and wanted.search(sel):
            keep.append("%s{%s}" % (sel, body))
    return "".join(keep)


def main(job):
    page_rel, out_rel, cap_rel, families = JOBS[job]
    page = open(os.path.join(ROOT, page_rel), encoding="utf-8").read()
    out_href = "../" + out_rel
    local = ""
    for href in re.findall(r'<link rel="stylesheet" href="(\.\./[^"]+\.css)"', page):
        if href != out_href:
            local += open(os.path.join(ROOT, "pages", href), encoding="utf-8").read()
    local += "".join(re.findall(r"<style[^>]*>(.*?)</style>", page, re.S))

    tokens = set(t for c in re.findall(r'class="([^"]*)"', page) for t in c.split())
    missing = sorted(t for t in tokens if t.startswith(families)
                     or not re.search(r"\.%s(?![\w-])" % re.escape(esc(t)), local))
    wanted = re.compile("|".join(r"\.%s(?![\w\\-])" % re.escape(esc(t)) for t in missing))

    cap = open(os.path.join(ROOT, cap_rel), encoding="utf-8").read()
    bundles = ""
    for href in dict.fromkeys(re.findall(r'<link rel="stylesheet" href="(/_next/static/[^"]+\.css)"', cap)):
        req = urllib.request.Request(BETA + href, headers={"Cookie": "gp-locale=en"})
        with urllib.request.urlopen(req, timeout=60) as r:
            bundles += r.read().decode("utf-8")
    picked = pick(bundles, wanted)

    defined = set(re.findall(r"(--[\w-]+)\s*:", local + picked))
    used = set(re.findall(r"var\((--[\w-]+)", picked))
    decls = []
    for v in sorted(used - defined):
        m = re.search(r"%s\s*:([^;}]+)" % re.escape(v), bundles)
        if m:
            decls.append("%s:%s" % (v, m.group(1).strip()))
    head = ("/* Generated by crawl/vendor_css.py %s from beta.goldenpi.com's production bundles: only the rules for\n"
            "   classes on %s that the page's local CSS does not define. Do not edit. */\n" % (job, page_rel))
    css = head + (":root{%s}" % ";".join(decls) if decls else "") + picked
    with open(os.path.join(ROOT, out_rel), "w", encoding="utf-8") as f:
        f.write(css)
    print("%s: %d classes missing locally, %d bytes of rules, %d variables" % (out_rel, len(missing), len(picked), len(decls)))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "fd")
